
package cn.bxd.sip.bxd.webservice.client.msgws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MessageCenterWebserviceService", targetNamespace = "http://webservice.messagecenter.efc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MessageCenterWebserviceService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws MessageException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "messageUnreadCount", targetNamespace = "http://webservice.messagecenter.efc.com/", className = "cn.bxd.sip.bxd.webservice.client.msgws.MessageUnreadCount")
    @ResponseWrapper(localName = "messageUnreadCountResponse", targetNamespace = "http://webservice.messagecenter.efc.com/", className = "cn.bxd.sip.bxd.webservice.client.msgws.MessageUnreadCountResponse")
    public String messageUnreadCount(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0)
        throws MessageException_Exception
    ;

    /**
     * 
     * @param jsonmsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendSmsMsg", targetNamespace = "http://webservice.messagecenter.efc.com/", className = "cn.bxd.sip.bxd.webservice.client.msgws.SendSmsMsg")
    @ResponseWrapper(localName = "sendSmsMsgResponse", targetNamespace = "http://webservice.messagecenter.efc.com/", className = "cn.bxd.sip.bxd.webservice.client.msgws.SendSmsMsgResponse")
    public String sendSmsMsg(
            @WebParam(name = "jsonmsg", targetNamespace = "")
                    String jsonmsg);

    /**
     * 
     * @param msguid
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "messageRead", targetNamespace = "http://webservice.messagecenter.efc.com/", className = "cn.bxd.sip.bxd.webservice.client.msgws.MessageRead")
    @ResponseWrapper(localName = "messageReadResponse", targetNamespace = "http://webservice.messagecenter.efc.com/", className = "cn.bxd.sip.bxd.webservice.client.msgws.MessageReadResponse")
    public String messageRead(
            @WebParam(name = "msguid", targetNamespace = "")
                    String msguid);

    /**
     * 
     * @param queryJson
     * @return
     *     returns java.lang.String
     * @throws MessageException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "userMessageQuery", targetNamespace = "http://webservice.messagecenter.efc.com/", className = "cn.bxd.sip.bxd.webservice.client.msgws.UserMessageQuery")
    @ResponseWrapper(localName = "userMessageQueryResponse", targetNamespace = "http://webservice.messagecenter.efc.com/", className = "cn.bxd.sip.bxd.webservice.client.msgws.UserMessageQueryResponse")
    public String userMessageQuery(
            @WebParam(name = "query_json", targetNamespace = "")
                    String queryJson)
        throws MessageException_Exception
    ;

    /**
     * 
     * @param jsonmsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMsg", targetNamespace = "http://webservice.messagecenter.efc.com/", className = "cn.bxd.sip.bxd.webservice.client.msgws.SendMsg")
    @ResponseWrapper(localName = "sendMsgResponse", targetNamespace = "http://webservice.messagecenter.efc.com/", className = "cn.bxd.sip.bxd.webservice.client.msgws.SendMsgResponse")
    public String sendMsg(
            @WebParam(name = "jsonmsg", targetNamespace = "")
                    String jsonmsg);

}
