
package cn.bxd.sip.bxd.webservice.client.msgws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "MessageException", targetNamespace = "http://webservice.messagecenter.efc.com/")
public class MessageException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MessageException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public MessageException_Exception(String message, MessageException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public MessageException_Exception(String message, MessageException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cn.bxd.sip.bxd.webservice.client.msgws.MessageException
     */
    public MessageException getFaultInfo() {
        return faultInfo;
    }

}
