
package cn.bxd.sip.his.webservice.hisws.invoke2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 *
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * HellWorld
     *
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.HelloWorldResponse")
    public String helloWorld();

    /**
     *  1.1.1	身份证号码查看患者信息
     *
     * @param synkey
     * @param synusername
     * @param cardno
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryPatientInfoByIdNO")
    @WebResult(name = "queryPatientInfoByIdNOResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryPatientInfoByIdNO", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryPatientInfoByIdNO")
    @ResponseWrapper(localName = "queryPatientInfoByIdNOResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryPatientInfoByIdNOResponse")
    public String queryPatientInfoByIdNO(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "cardno", targetNamespace = "http://tempuri.org/")
                    String cardno);

    /**
     *  1.1.2	社保、银行、就诊卡号查看患者信息
     *
     * @param synkey
     * @param bankcardnumber
     * @param synusername
     * @param visitcardno
     * @param socialsecurityno
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryPatientInfoBySocialsecurityNO")
    @WebResult(name = "queryPatientInfoBySocialsecurityNOResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryPatientInfoBySocialsecurityNO", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryPatientInfoBySocialsecurityNO")
    @ResponseWrapper(localName = "queryPatientInfoBySocialsecurityNOResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryPatientInfoBySocialsecurityNOResponse")
    public String queryPatientInfoBySocialsecurityNO(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "socialsecurityno", targetNamespace = "http://tempuri.org/")
                    String socialsecurityno,
            @WebParam(name = "bankcardnumber", targetNamespace = "http://tempuri.org/")
                    String bankcardnumber,
            @WebParam(name = "visitcardno", targetNamespace = "http://tempuri.org/")
                    String visitcardno);

    /**
     *  1.1.3	患者档案建立
     *
     * @param synkey
     * @param synusername
     * @param hiuser
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doCreatCardInfo")
    @WebResult(name = "doCreatCardInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doCreatCardInfo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.DoCreatCardInfo")
    @ResponseWrapper(localName = "doCreatCardInfoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.DoCreatCardInfoResponse")
    public String doCreatCardInfo(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "hiuser", targetNamespace = "http://tempuri.org/")
                    String hiuser);

    /**
     *  1.1.4	查询检查,检验数据打印状态状态
     *
     * @param synkey
     * @param synusername
     * @param reportnos
     * @param reporttype
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryExaminationRecordStatus")
    @WebResult(name = "queryExaminationRecordStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryExaminationRecordStatus", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryExaminationRecordStatus")
    @ResponseWrapper(localName = "queryExaminationRecordStatusResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryExaminationRecordStatusResponse")
    public String queryExaminationRecordStatus(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "reportnos", targetNamespace = "http://tempuri.org/")
                    String reportnos,
            @WebParam(name = "reporttype", targetNamespace = "http://tempuri.org/")
                    String reporttype);

    /**
     *  1.1.5	更新检查,检验数据打印状态
     *
     * @param synkey
     * @param synusername
     * @param reportnos
     * @param reporttype
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/updateExaminationRecordStatus")
    @WebResult(name = "updateExaminationRecordStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "updateExaminationRecordStatus", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.UpdateExaminationRecordStatus")
    @ResponseWrapper(localName = "updateExaminationRecordStatusResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.UpdateExaminationRecordStatusResponse")
    public String updateExaminationRecordStatus(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "reportnos", targetNamespace = "http://tempuri.org/")
                    String reportnos,
            @WebParam(name = "reporttype", targetNamespace = "http://tempuri.org/")
                    String reporttype);

    /**
     *  1.1.6	获取检查,检验数据
     *
     * @param synkey
     * @param startdate
     * @param synusername
     * @param patientno
     * @param enddate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryExaminationRecordList")
    @WebResult(name = "queryExaminationRecordListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryExaminationRecordList", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryExaminationRecordList")
    @ResponseWrapper(localName = "queryExaminationRecordListResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryExaminationRecordListResponse")
    public String queryExaminationRecordList(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "patientno", targetNamespace = "http://tempuri.org/")
                    String patientno,
            @WebParam(name = "startdate", targetNamespace = "http://tempuri.org/")
                    String startdate,
            @WebParam(name = "enddate", targetNamespace = "http://tempuri.org/")
                    String enddate);

    /**
     *  1.1.7更新患者信息
     *
     * @param synkey
     * @param bankcardnumber
     * @param synusername
     * @param visitcardno
     * @param cardno
     * @param socialsecurityno
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/updatePatientInfo")
    @WebResult(name = "updatePatientInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "updatePatientInfo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.UpdatePatientInfo")
    @ResponseWrapper(localName = "updatePatientInfoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.UpdatePatientInfoResponse")
    public String updatePatientInfo(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "cardno", targetNamespace = "http://tempuri.org/")
                    String cardno,
            @WebParam(name = "socialsecurityno", targetNamespace = "http://tempuri.org/")
                    String socialsecurityno,
            @WebParam(name = "bankcardnumber", targetNamespace = "http://tempuri.org/")
                    String bankcardnumber,
            @WebParam(name = "visitcardno", targetNamespace = "http://tempuri.org/")
                    String visitcardno);

    /**
     *  1.2.1	查询医生列表信息
     *
     * @param synkey
     * @param synusername
     * @param departmentorganid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryDoctorList")
    @WebResult(name = "queryDoctorListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryDoctorList", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryDoctorList")
    @ResponseWrapper(localName = "queryDoctorListResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryDoctorListResponse")
    public String queryDoctorList(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "departmentorganid", targetNamespace = "http://tempuri.org/")
                    String departmentorganid);

    /**
     *  1.2.2	根据科室Id查询科室信息
     *
     * @param synkey
     * @param synusername
     * @param organid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryDepartmentById")
    @WebResult(name = "queryDepartmentByIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryDepartmentById", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryDepartmentById")
    @ResponseWrapper(localName = "queryDepartmentByIdResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryDepartmentByIdResponse")
    public String queryDepartmentById(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "organid", targetNamespace = "http://tempuri.org/")
                    String organid);

    /**
     *  1.2.3	查询部门列表信息
     *
     * @param synkey
     * @param synusername
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryDepartmentList")
    @WebResult(name = "queryDepartmentListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryDepartmentList", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryDepartmentList")
    @ResponseWrapper(localName = "queryDepartmentListResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryDepartmentListResponse")
    public String queryDepartmentList(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey);

    /**
     *  1.2.4	根据医生Id查询医生信息
     *
     * @param synkey
     * @param synusername
     * @param organdoctorid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryDoctorById")
    @WebResult(name = "queryDoctorByIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryDoctorById", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryDoctorById")
    @ResponseWrapper(localName = "queryDoctorByIdResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryDoctorByIdResponse")
    public String queryDoctorById(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "organdoctorid", targetNamespace = "http://tempuri.org/")
                    String organdoctorid);

    /**
     *  1.3.1	取消预约
     *
     * @param synkey
     * @param synusername
     * @param patientno
     * @param sourcemark
     * @param sourcedate
     * @param departmentorganid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doRegCancel")
    @WebResult(name = "doRegCancelResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doRegCancel", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.DoRegCancel")
    @ResponseWrapper(localName = "doRegCancelResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.DoRegCancelResponse")
    public String doRegCancel(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "sourcemark", targetNamespace = "http://tempuri.org/")
                    String sourcemark,
            @WebParam(name = "patientno", targetNamespace = "http://tempuri.org/")
                    String patientno,
            @WebParam(name = "sourcedate", targetNamespace = "http://tempuri.org/")
                    String sourcedate,
            @WebParam(name = "departmentorganid", targetNamespace = "http://tempuri.org/")
                    String departmentorganid);

    /**
     *  1.3.2	预约挂号
     *
     * @param synkey
     * @param doregin
     * @param synusername
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doReg")
    @WebResult(name = "doRegResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doReg", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.DoReg")
    @ResponseWrapper(localName = "doRegResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.DoRegResponse")
    public String doReg(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "doregin", targetNamespace = "http://tempuri.org/")
                    String doregin);

    /**
     *  1.3.3	查询号源
     *
     * @param synkey
     * @param startdate
     * @param synusername
     * @param enddate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryToRegDoctorList")
    @WebResult(name = "queryToRegDoctorListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryToRegDoctorList", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryToRegDoctorList")
    @ResponseWrapper(localName = "queryToRegDoctorListResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryToRegDoctorListResponse")
    public String queryToRegDoctorList(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "startdate", targetNamespace = "http://tempuri.org/")
                    String startdate,
            @WebParam(name = "enddate", targetNamespace = "http://tempuri.org/")
                    String enddate);

    /**
     *  1.3.4	根据医生ID查询号源
     *
     * @param synkey
     * @param startdate
     * @param synusername
     * @param organdoctorid
     * @param enddate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryToRegDoctorListByDoctorId")
    @WebResult(name = "queryToRegDoctorListByDoctorIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryToRegDoctorListByDoctorId", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryToRegDoctorListByDoctorId")
    @ResponseWrapper(localName = "queryToRegDoctorListByDoctorIdResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryToRegDoctorListByDoctorIdResponse")
    public String queryToRegDoctorListByDoctorId(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "startdate", targetNamespace = "http://tempuri.org/")
                    String startdate,
            @WebParam(name = "enddate", targetNamespace = "http://tempuri.org/")
                    String enddate,
            @WebParam(name = "organdoctorid", targetNamespace = "http://tempuri.org/")
                    String organdoctorid);

    /**
     *  1.3.5	排取人数
     *
     * @param synkey
     * @param synusername
     * @param patientno
     * @param sourcemark
     * @param sourcedate
     * @param departmentorganid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryRegWaitNum")
    @WebResult(name = "queryRegWaitNumResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryRegWaitNum", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryRegWaitNum")
    @ResponseWrapper(localName = "queryRegWaitNumResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryRegWaitNumResponse")
    public String queryRegWaitNum(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "sourcemark", targetNamespace = "http://tempuri.org/")
                    String sourcemark,
            @WebParam(name = "patientno", targetNamespace = "http://tempuri.org/")
                    String patientno,
            @WebParam(name = "sourcedate", targetNamespace = "http://tempuri.org/")
                    String sourcedate,
            @WebParam(name = "departmentorganid", targetNamespace = "http://tempuri.org/")
                    String departmentorganid);

    /**
     *  1.3.6	取号查询接口
     *
     * @param synkey
     * @param synusername
     * @param patientno
     * @param sourcemark
     * @param sourcedate
     * @param departmentorganid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryTaketheNo")
    @WebResult(name = "queryTaketheNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryTaketheNo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryTaketheNo")
    @ResponseWrapper(localName = "queryTaketheNoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryTaketheNoResponse")
    public String queryTaketheNo(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "sourcemark", targetNamespace = "http://tempuri.org/")
                    String sourcemark,
            @WebParam(name = "patientno", targetNamespace = "http://tempuri.org/")
                    String patientno,
            @WebParam(name = "sourcedate", targetNamespace = "http://tempuri.org/")
                    String sourcedate,
            @WebParam(name = "departmentorganid", targetNamespace = "http://tempuri.org/")
                    String departmentorganid);

    /**
     *  1.3.7	门诊取号
     *
     * @param synkey
     * @param doregin
     * @param synusername
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doTaketheNo")
    @WebResult(name = "doTaketheNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doTaketheNo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.DoTaketheNo")
    @ResponseWrapper(localName = "doTaketheNoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.DoTaketheNoResponse")
    public String doTaketheNo(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "doregin", targetNamespace = "http://tempuri.org/")
                    String doregin);

    /**
     *  1.3.8	预约当天并取号
     *
     * @param synkey
     * @param doregin
     * @param synusername
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doRegAndTaketheNo")
    @WebResult(name = "doRegAndTaketheNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doRegAndTaketheNo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.DoRegAndTaketheNo")
    @ResponseWrapper(localName = "doRegAndTaketheNoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.DoRegAndTaketheNoResponse")
    public String doRegAndTaketheNo(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "doregin", targetNamespace = "http://tempuri.org/")
                    String doregin);

    /**
     *  1.3.9	查询未取号的预约挂号
     *
     * @param synkey
     * @param synusername
     * @param patientno
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryRegBypatientNo")
    @WebResult(name = "queryRegBypatientNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryRegBypatientNo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryRegBypatientNo")
    @ResponseWrapper(localName = "queryRegBypatientNoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryRegBypatientNoResponse")
    public String queryRegBypatientNo(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "patientno", targetNamespace = "http://tempuri.org/")
                    String patientno);

    /**
     *  1.3.10	查询医生号源时间段
     *
     * @param sourcetimetype
     * @param synkey
     * @param synusername
     * @param organdoctorid
     * @param sourcedate
     * @param departmentorganid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryToRegDoctorTimes")
    @WebResult(name = "queryToRegDoctorTimesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryToRegDoctorTimes", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryToRegDoctorTimes")
    @ResponseWrapper(localName = "queryToRegDoctorTimesResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryToRegDoctorTimesResponse")
    public String queryToRegDoctorTimes(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "sourcedate", targetNamespace = "http://tempuri.org/")
                    String sourcedate,
            @WebParam(name = "organdoctorid", targetNamespace = "http://tempuri.org/")
                    String organdoctorid,
            @WebParam(name = "departmentorganid", targetNamespace = "http://tempuri.org/")
                    String departmentorganid,
            @WebParam(name = "sourcetimetype", targetNamespace = "http://tempuri.org/")
                    String sourcetimetype);

    /**
     *  1.3.11	查询挂号状态与支付状态
     *
     * @param synkey
     * @param synusername
     * @param sourcemark
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryAppointmentPayStatus")
    @WebResult(name = "queryAppointmentPayStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryAppointmentPayStatus", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryAppointmentPayStatus")
    @ResponseWrapper(localName = "queryAppointmentPayStatusResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryAppointmentPayStatusResponse")
    public String queryAppointmentPayStatus(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "sourcemark", targetNamespace = "http://tempuri.org/")
                    String sourcemark);

    /**
     *  1.3.13	查询医生当前排队人数
     *
     * @param synkey
     * @param synusername
     * @param organdoctorid
     * @param departmentorganid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryDoctorRegWaitNum")
    @WebResult(name = "queryDoctorRegWaitNumResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryDoctorRegWaitNum", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryDoctorRegWaitNum")
    @ResponseWrapper(localName = "queryDoctorRegWaitNumResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryDoctorRegWaitNumResponse")
    public String queryDoctorRegWaitNum(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "organdoctorid", targetNamespace = "http://tempuri.org/")
                    String organdoctorid,
            @WebParam(name = "departmentorganid", targetNamespace = "http://tempuri.org/")
                    String departmentorganid);

    /**
     *  1.3.15	查询挂号费
     *
     * @param sourcetimetype
     * @param synkey
     * @param synusername
     * @param organdoctorid
     * @param patientno
     * @param timestypeno
     * @param sourcedate
     * @param departmentorganid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doregFeeInterface")
    @WebResult(name = "doregFeeInterfaceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doregFeeInterface", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.DoregFeeInterface")
    @ResponseWrapper(localName = "doregFeeInterfaceResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.DoregFeeInterfaceResponse")
    public String doregFeeInterface(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "organdoctorid", targetNamespace = "http://tempuri.org/")
                    String organdoctorid,
            @WebParam(name = "departmentorganid", targetNamespace = "http://tempuri.org/")
                    String departmentorganid,
            @WebParam(name = "patientno", targetNamespace = "http://tempuri.org/")
                    String patientno,
            @WebParam(name = "sourcedate", targetNamespace = "http://tempuri.org/")
                    String sourcedate,
            @WebParam(name = "timestypeno", targetNamespace = "http://tempuri.org/")
                    String timestypeno,
            @WebParam(name = "sourcetimetype", targetNamespace = "http://tempuri.org/")
                    String sourcetimetype);

    /**
     *  1.3.16	获取挂号医保信息
     *
     * @param synkey
     * @param doregin
     * @param synusername
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doRegMedicareInfo")
    @WebResult(name = "doRegMedicareInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doRegMedicareInfo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.DoRegMedicareInfo")
    @ResponseWrapper(localName = "doRegMedicareInfoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.DoRegMedicareInfoResponse")
    public String doRegMedicareInfo(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "doregin", targetNamespace = "http://tempuri.org/")
                    String doregin);

    /**
     *  1.4.1	待交费列表
     *
     * @param medicaremess
     * @param synkey
     * @param synusername
     * @param patientno
     * @param medicaretype
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryToPayRecipeInfoList")
    @WebResult(name = "queryToPayRecipeInfoListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryToPayRecipeInfoList", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryToPayRecipeInfoList")
    @ResponseWrapper(localName = "queryToPayRecipeInfoListResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryToPayRecipeInfoListResponse")
    public String queryToPayRecipeInfoList(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "patientno", targetNamespace = "http://tempuri.org/")
                    String patientno,
            @WebParam(name = "medicaretype", targetNamespace = "http://tempuri.org/")
                    String medicaretype,
            @WebParam(name = "medicaremess", targetNamespace = "http://tempuri.org/")
                    String medicaremess);

    /**
     *  1.4.2	已交费列表
     *
     * @param synkey
     * @param startdate
     * @param synusername
     * @param patientno
     * @param enddate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryPaymentRecordList")
    @WebResult(name = "queryPaymentRecordListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryPaymentRecordList", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryPaymentRecordList")
    @ResponseWrapper(localName = "queryPaymentRecordListResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryPaymentRecordListResponse")
    public String queryPaymentRecordList(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "patientno", targetNamespace = "http://tempuri.org/")
                    String patientno,
            @WebParam(name = "startdate", targetNamespace = "http://tempuri.org/")
                    String startdate,
            @WebParam(name = "enddate", targetNamespace = "http://tempuri.org/")
                    String enddate);

    /**
     *  1.4.3	根据处方编号获取处方信息
     *
     * @param medicaremess
     * @param synkey
     * @param hifeeno
     * @param synusername
     * @param patientno
     * @param medicaretype
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryToPayRecipeByHiFeeNo")
    @WebResult(name = "queryToPayRecipeByHiFeeNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryToPayRecipeByHiFeeNo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryToPayRecipeByHiFeeNo")
    @ResponseWrapper(localName = "queryToPayRecipeByHiFeeNoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryToPayRecipeByHiFeeNoResponse")
    public String queryToPayRecipeByHiFeeNo(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "hifeeno", targetNamespace = "http://tempuri.org/")
                    String hifeeno,
            @WebParam(name = "patientno", targetNamespace = "http://tempuri.org/")
                    String patientno,
            @WebParam(name = "medicaretype", targetNamespace = "http://tempuri.org/")
                    String medicaretype,
            @WebParam(name = "medicaremess", targetNamespace = "http://tempuri.org/")
                    String medicaremess);

    /**
     *  1.4.4	更新打票状态（处方小票）
     *
     * @param synkey
     * @param synusername
     * @param hifeenos
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/updateRecipeStatusStatus")
    @WebResult(name = "updateRecipeStatusStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "updateRecipeStatusStatus", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.UpdateRecipeStatusStatus")
    @ResponseWrapper(localName = "updateRecipeStatusStatusResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.UpdateRecipeStatusStatusResponse")
    public String updateRecipeStatusStatus(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "hifeenos", targetNamespace = "http://tempuri.org/")
                    String hifeenos);

    /**
     *  1.4.5	处方支付
     *
     * @param synkey
     * @param synusername
     * @param paymentdata
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doPay")
    @WebResult(name = "doPayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doPay", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.DoPay")
    @ResponseWrapper(localName = "doPayResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.DoPayResponse")
    public String doPay(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "paymentdata", targetNamespace = "http://tempuri.org/")
                    String paymentdata);

    /**
     *  1.4.6	查询支付状态
     *
     * @param synkey
     * @param payrecord
     * @param hifeeno
     * @param synusername
     * @param overmoney
     * @param paytype
     * @param medicaremoney
     * @param overrecord
     * @param socialsecurityno
     * @param paymoney
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryPayStatus")
    @WebResult(name = "queryPayStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryPayStatus", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryPayStatus")
    @ResponseWrapper(localName = "queryPayStatusResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryPayStatusResponse")
    public String queryPayStatus(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "hifeeno", targetNamespace = "http://tempuri.org/")
                    String hifeeno,
            @WebParam(name = "paytype", targetNamespace = "http://tempuri.org/")
                    String paytype,
            @WebParam(name = "payrecord", targetNamespace = "http://tempuri.org/")
                    String payrecord,
            @WebParam(name = "paymoney", targetNamespace = "http://tempuri.org/")
                    String paymoney,
            @WebParam(name = "medicaremoney", targetNamespace = "http://tempuri.org/")
                    String medicaremoney,
            @WebParam(name = "socialsecurityno", targetNamespace = "http://tempuri.org/")
                    String socialsecurityno,
            @WebParam(name = "overrecord", targetNamespace = "http://tempuri.org/")
                    String overrecord,
            @WebParam(name = "overmoney", targetNamespace = "http://tempuri.org/")
                    String overmoney);

    /**
     *  1.4.7	获取发票打印列表
     *
     * @param synkey
     * @param synusername
     * @param patientno
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryInvoiceReportList")
    @WebResult(name = "queryInvoiceReportListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryInvoiceReportList", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryInvoiceReportList")
    @ResponseWrapper(localName = "queryInvoiceReportListResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryInvoiceReportListResponse")
    public String queryInvoiceReportList(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "patientno", targetNamespace = "http://tempuri.org/")
                    String patientno);

    /**
     *  1.4.8	获取发票列表详情
     *
     * @param synkey
     * @param synusername
     * @param outinvoiceid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryInvoiceDetail")
    @WebResult(name = "queryInvoiceDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryInvoiceDetail", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryInvoiceDetail")
    @ResponseWrapper(localName = "queryInvoiceDetailResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryInvoiceDetailResponse")
    public String queryInvoiceDetail(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "outinvoiceid", targetNamespace = "http://tempuri.org/")
                    String outinvoiceid);

    /**
     *  1.4.9	更新发票打印状态
     *
     * @param synkey
     * @param synusername
     * @param visitcardno
     * @param cardno
     * @param cardtypeid
     * @param outinvoiceid
     * @param clinictrueno
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/updateInvoiceStatus")
    @WebResult(name = "updateInvoiceStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "updateInvoiceStatus", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.UpdateInvoiceStatus")
    @ResponseWrapper(localName = "updateInvoiceStatusResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.UpdateInvoiceStatusResponse")
    public String updateInvoiceStatus(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "outinvoiceid", targetNamespace = "http://tempuri.org/")
                    String outinvoiceid,
            @WebParam(name = "clinictrueno", targetNamespace = "http://tempuri.org/")
                    String clinictrueno,
            @WebParam(name = "cardtypeid", targetNamespace = "http://tempuri.org/")
                    String cardtypeid,
            @WebParam(name = "cardno", targetNamespace = "http://tempuri.org/")
                    String cardno,
            @WebParam(name = "visitcardno", targetNamespace = "http://tempuri.org/")
                    String visitcardno);

    /**
     *  1.5.1	查询患者住院信息
     *
     * @param synkey
     * @param bankcardnumber
     * @param synusername
     * @param visitcardno
     * @param cardno
     * @param socialsecurityno
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryPatientInHosInfo")
    @WebResult(name = "queryPatientInHosInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryPatientInHosInfo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryPatientInHosInfo")
    @ResponseWrapper(localName = "queryPatientInHosInfoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.QueryPatientInHosInfoResponse")
    public String queryPatientInHosInfo(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "cardno", targetNamespace = "http://tempuri.org/")
                    String cardno,
            @WebParam(name = "visitcardno", targetNamespace = "http://tempuri.org/")
                    String visitcardno,
            @WebParam(name = "socialsecurityno", targetNamespace = "http://tempuri.org/")
                    String socialsecurityno,
            @WebParam(name = "bankcardnumber", targetNamespace = "http://tempuri.org/")
                    String bankcardnumber);

    /**
     *  1.5.5	住院押金补缴
     *
     * @param inhosno
     * @param synkey
     * @param bedno
     * @param payrecord
     * @param synusername
     * @param paytype
     * @param terminalcode
     * @param payreturn
     * @param paymoney
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/inpatientPayment")
    @WebResult(name = "inpatientPaymentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "inpatientPayment", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.InpatientPayment")
    @ResponseWrapper(localName = "inpatientPaymentResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.InpatientPaymentResponse")
    public String inpatientPayment(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "inhosno", targetNamespace = "http://tempuri.org/")
                    String inhosno,
            @WebParam(name = "bedno", targetNamespace = "http://tempuri.org/")
                    String bedno,
            @WebParam(name = "paytype", targetNamespace = "http://tempuri.org/")
                    String paytype,
            @WebParam(name = "payrecord", targetNamespace = "http://tempuri.org/")
                    String payrecord,
            @WebParam(name = "paymoney", targetNamespace = "http://tempuri.org/")
                    String paymoney,
            @WebParam(name = "payreturn", targetNamespace = "http://tempuri.org/")
                    String payreturn,
            @WebParam(name = "terminalcode", targetNamespace = "http://tempuri.org/")
                    String terminalcode);

    /**
     *  1.5.7	住院清单明细
     *
     * @param inhosno
     * @param synkey
     * @param startdate
     * @param synusername
     * @param patientno
     * @param enddate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/inHosDetail")
    @WebResult(name = "inHosDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "inHosDetail", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.InHosDetail")
    @ResponseWrapper(localName = "inHosDetailResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.InHosDetailResponse")
    public String inHosDetail(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "patientno", targetNamespace = "http://tempuri.org/")
                    String patientno,
            @WebParam(name = "inhosno", targetNamespace = "http://tempuri.org/")
                    String inhosno,
            @WebParam(name = "startdate", targetNamespace = "http://tempuri.org/")
                    String startdate,
            @WebParam(name = "enddate", targetNamespace = "http://tempuri.org/")
                    String enddate);

    /**
     *  1.5.6	押金明细查询
     *
     * @param inhosno
     * @param synkey
     * @param startdate
     * @param synusername
     * @param patientno
     * @param enddate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/payDetail")
    @WebResult(name = "payDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "payDetail", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.PayDetail")
    @ResponseWrapper(localName = "payDetailResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke2.PayDetailResponse")
    public String payDetail(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "patientno", targetNamespace = "http://tempuri.org/")
                    String patientno,
            @WebParam(name = "inhosno", targetNamespace = "http://tempuri.org/")
                    String inhosno,
            @WebParam(name = "startdate", targetNamespace = "http://tempuri.org/")
                    String startdate,
            @WebParam(name = "enddate", targetNamespace = "http://tempuri.org/")
                    String enddate);

}
