
package cn.bxd.sip.his.webservice.hisws.invoke3.inhos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InHosSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InHosSoap {


    /**
     * 查询患者住院信息
     * 
     * @param cardNo
     * @param socialsecurityNO
     * @param synKey
     * @param synUserName
     * @param visitCardNo
     * @param bankCardNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryPatientInHosInfo")
    @WebResult(name = "queryPatientInHosInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryPatientInHosInfo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.inhos.QueryPatientInHosInfo")
    @ResponseWrapper(localName = "queryPatientInHosInfoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.inhos.QueryPatientInHosInfoResponse")
    public String queryPatientInHosInfo(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "cardNo", targetNamespace = "http://tempuri.org/")
        String cardNo,
        @WebParam(name = "visitCardNo", targetNamespace = "http://tempuri.org/")
        String visitCardNo,
        @WebParam(name = "socialsecurityNO", targetNamespace = "http://tempuri.org/")
        String socialsecurityNO,
        @WebParam(name = "bankCardNumber", targetNamespace = "http://tempuri.org/")
        String bankCardNumber);

    /**
     * 住院清单明细
     * 
     * @param startDate
     * @param synKey
     * @param synUserName
     * @param endDate
     * @param patientNo
     * @param inHosNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/inHosDetail")
    @WebResult(name = "inHosDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "inHosDetail", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.inhos.InHosDetail")
    @ResponseWrapper(localName = "inHosDetailResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.inhos.InHosDetailResponse")
    public String inHosDetail(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
        String patientNo,
        @WebParam(name = "inHosNo", targetNamespace = "http://tempuri.org/")
        String inHosNo,
        @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 住院每日清单
     * 
     * @param startDate
     * @param synKey
     * @param synUserName
     * @param endDate
     * @param patientNo
     * @param inHosNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/inHosDaily")
    @WebResult(name = "inHosDailyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "inHosDaily", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.inhos.InHosDaily")
    @ResponseWrapper(localName = "inHosDailyResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.inhos.InHosDailyResponse")
    public String inHosDaily(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
        String patientNo,
        @WebParam(name = "inHosNo", targetNamespace = "http://tempuri.org/")
        String inHosNo,
        @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 住院押金
     * 
     * @param startDate
     * @param synKey
     * @param synUserName
     * @param endDate
     * @param patientNo
     * @param inHosNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/payDetail")
    @WebResult(name = "payDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "payDetail", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.inhos.PayDetail")
    @ResponseWrapper(localName = "payDetailResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.inhos.PayDetailResponse")
    public String payDetail(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
        String patientNo,
        @WebParam(name = "inHosNo", targetNamespace = "http://tempuri.org/")
        String inHosNo,
        @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 住院押金补缴
     * 
     * @param payMoney
     * @param terminalCode
     * @param synKey
     * @param payRecord
     * @param bedNo
     * @param payType
     * @param synUserName
     * @param payReturn
     * @param inHosNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/inpatientPayment")
    @WebResult(name = "inpatientPaymentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "inpatientPayment", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.inhos.InpatientPayment")
    @ResponseWrapper(localName = "inpatientPaymentResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.inhos.InpatientPaymentResponse")
    public String inpatientPayment(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "inHosNo", targetNamespace = "http://tempuri.org/")
        String inHosNo,
        @WebParam(name = "bedNo", targetNamespace = "http://tempuri.org/")
        String bedNo,
        @WebParam(name = "payType", targetNamespace = "http://tempuri.org/")
        String payType,
        @WebParam(name = "payRecord", targetNamespace = "http://tempuri.org/")
        String payRecord,
        @WebParam(name = "payMoney", targetNamespace = "http://tempuri.org/")
        String payMoney,
        @WebParam(name = "payReturn", targetNamespace = "http://tempuri.org/")
        String payReturn,
        @WebParam(name = "terminalCode", targetNamespace = "http://tempuri.org/")
        String terminalCode);

}
