
package cn.bxd.sip.his.webservice.hisws.invoke3.reg;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RegSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RegSoap {


    /**
     * 取消预约
     * 
     * @param synKey
     * @param departmentorganId
     * @param sourceMark
     * @param sourceDate
     * @param synUserName
     * @param patientNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doRegCancel")
    @WebResult(name = "doRegCancelResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doRegCancel", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.DoRegCancel")
    @ResponseWrapper(localName = "doRegCancelResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.DoRegCancelResponse")
    public String doRegCancel(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "sourceMark", targetNamespace = "http://tempuri.org/")
        String sourceMark,
        @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
        String patientNo,
        @WebParam(name = "sourceDate", targetNamespace = "http://tempuri.org/")
        String sourceDate,
        @WebParam(name = "departmentorganId", targetNamespace = "http://tempuri.org/")
        String departmentorganId);

    /**
     * 预约挂号
     * 
     * @param synKey
     * @param synUserName
     * @param doRegIn
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doReg")
    @WebResult(name = "doRegResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doReg", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.DoReg")
    @ResponseWrapper(localName = "doRegResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.DoRegResponse")
    public String doReg(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "DoRegIn", targetNamespace = "http://tempuri.org/")
        String doRegIn);

    /**
     * 查询号源
     * 
     * @param startDate
     * @param synKey
     * @param synUserName
     * @param endDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryToRegDoctorList")
    @WebResult(name = "queryToRegDoctorListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryToRegDoctorList", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.QueryToRegDoctorList")
    @ResponseWrapper(localName = "queryToRegDoctorListResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.QueryToRegDoctorListResponse")
    public String queryToRegDoctorList(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 根据医生查询号源
     * 
     * @param startDate
     * @param synKey
     * @param synUserName
     * @param doctorID
     * @param endDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryToRegDoctorListByDoctorId")
    @WebResult(name = "queryToRegDoctorListByDoctorIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryToRegDoctorListByDoctorId", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.QueryToRegDoctorListByDoctorId")
    @ResponseWrapper(localName = "queryToRegDoctorListByDoctorIdResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.QueryToRegDoctorListByDoctorIdResponse")
    public String queryToRegDoctorListByDoctorId(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate,
        @WebParam(name = "doctorID", targetNamespace = "http://tempuri.org/")
        String doctorID);

    /**
     * 排取人数
     * 
     * @param synKey
     * @param departmentorganId
     * @param sourceMark
     * @param sourceDate
     * @param synUserName
     * @param patientNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryRegWaitNum")
    @WebResult(name = "queryRegWaitNumResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryRegWaitNum", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.QueryRegWaitNum")
    @ResponseWrapper(localName = "queryRegWaitNumResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.QueryRegWaitNumResponse")
    public String queryRegWaitNum(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "sourceMark", targetNamespace = "http://tempuri.org/")
        String sourceMark,
        @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
        String patientNo,
        @WebParam(name = "sourceDate", targetNamespace = "http://tempuri.org/")
        String sourceDate,
        @WebParam(name = "departmentorganId", targetNamespace = "http://tempuri.org/")
        String departmentorganId);

    /**
     * 查询医生号源时间段
     * 
     * @param synKey
     * @param departmentorganId
     * @param sourceTimeType
     * @param organdoctorId
     * @param sourceDate
     * @param synUserName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryToRegDoctorTimes")
    @WebResult(name = "queryToRegDoctorTimesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryToRegDoctorTimes", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.QueryToRegDoctorTimes")
    @ResponseWrapper(localName = "queryToRegDoctorTimesResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.QueryToRegDoctorTimesResponse")
    public String queryToRegDoctorTimes(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "sourceDate", targetNamespace = "http://tempuri.org/")
        String sourceDate,
        @WebParam(name = "organdoctorId", targetNamespace = "http://tempuri.org/")
        String organdoctorId,
        @WebParam(name = "departmentorganId", targetNamespace = "http://tempuri.org/")
        String departmentorganId,
        @WebParam(name = "sourceTimeType", targetNamespace = "http://tempuri.org/")
        String sourceTimeType);

    /**
     * 查询医生当前排队人数
     * 
     * @param synKey
     * @param departmentorganId
     * @param organdoctorId
     * @param synUserName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryDoctorRegWaitNum")
    @WebResult(name = "queryDoctorRegWaitNumResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryDoctorRegWaitNum", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.QueryDoctorRegWaitNum")
    @ResponseWrapper(localName = "queryDoctorRegWaitNumResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.QueryDoctorRegWaitNumResponse")
    public String queryDoctorRegWaitNum(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "organdoctorId", targetNamespace = "http://tempuri.org/")
        String organdoctorId,
        @WebParam(name = "departmentorganId", targetNamespace = "http://tempuri.org/")
        String departmentorganId);

    /**
     * 取号查询接口
     * 
     * @param synKey
     * @param departmentorganId
     * @param sourceMark
     * @param sourceDate
     * @param synUserName
     * @param patientNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryTaketheNo")
    @WebResult(name = "queryTaketheNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryTaketheNo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.QueryTaketheNo")
    @ResponseWrapper(localName = "queryTaketheNoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.QueryTaketheNoResponse")
    public String queryTaketheNo(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "sourceMark", targetNamespace = "http://tempuri.org/")
        String sourceMark,
        @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
        String patientNo,
        @WebParam(name = "sourceDate", targetNamespace = "http://tempuri.org/")
        String sourceDate,
        @WebParam(name = "departmentorganId", targetNamespace = "http://tempuri.org/")
        String departmentorganId);

    /**
     * 取号
     * 
     * @param payMoney
     * @param synKey
     * @param departmentorganId
     * @param sourceMark
     * @param payRecord
     * @param sourceDate
     * @param payType
     * @param synUserName
     * @param patientNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doTaketheNo")
    @WebResult(name = "doTaketheNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doTaketheNo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.DoTaketheNo")
    @ResponseWrapper(localName = "doTaketheNoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.DoTaketheNoResponse")
    public String doTaketheNo(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "sourceMark", targetNamespace = "http://tempuri.org/")
        String sourceMark,
        @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
        String patientNo,
        @WebParam(name = "sourceDate", targetNamespace = "http://tempuri.org/")
        String sourceDate,
        @WebParam(name = "departmentorganId", targetNamespace = "http://tempuri.org/")
        String departmentorganId,
        @WebParam(name = "payType", targetNamespace = "http://tempuri.org/")
        String payType,
        @WebParam(name = "payRecord", targetNamespace = "http://tempuri.org/")
        String payRecord,
        @WebParam(name = "payMoney", targetNamespace = "http://tempuri.org/")
        String payMoney);

    /**
     * 预约当天并取号
     * 
     * @param synKey
     * @param synUserName
     * @param doRegIn
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doRegAndTaketheNo")
    @WebResult(name = "doRegAndTaketheNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doRegAndTaketheNo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.DoRegAndTaketheNo")
    @ResponseWrapper(localName = "doRegAndTaketheNoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.DoRegAndTaketheNoResponse")
    public String doRegAndTaketheNo(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "DoRegIn", targetNamespace = "http://tempuri.org/")
        String doRegIn);

    /**
     * 查询未取号的预约挂号
     * 
     * @param synKey
     * @param synUserName
     * @param patientNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryRegBypatientNo")
    @WebResult(name = "queryRegBypatientNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryRegBypatientNo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.QueryRegBypatientNo")
    @ResponseWrapper(localName = "queryRegBypatientNoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.QueryRegBypatientNoResponse")
    public String queryRegBypatientNo(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
        String patientNo);

    /**
     * 查询挂号支付状态
     * 
     * @param synKey
     * @param sourceMark
     * @param synUserName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryAppointmentPayStatus")
    @WebResult(name = "queryAppointmentPayStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryAppointmentPayStatus", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.QueryAppointmentPayStatus")
    @ResponseWrapper(localName = "queryAppointmentPayStatusResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.QueryAppointmentPayStatusResponse")
    public String queryAppointmentPayStatus(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "sourceMark", targetNamespace = "http://tempuri.org/")
        String sourceMark);

    /**
     * 医生停诊
     * 
     * @param paramList
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doctorStopped")
    @WebResult(name = "doctorStoppedResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doctorStopped", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.DoctorStopped")
    @ResponseWrapper(localName = "doctorStoppedResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.DoctorStoppedResponse")
    public String doctorStopped(
        @WebParam(name = "paramList", targetNamespace = "http://tempuri.org/")
        String paramList);

    /**
     * 挂号费
     * 
     * @param synKey
     * @param departmentorganId
     * @param sourceTimeType
     * @param sourceDate
     * @param organdoctorId
     * @param synUserName
     * @param timestypeNo
     * @param patientNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doregFeeInterface")
    @WebResult(name = "doregFeeInterfaceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doregFeeInterface", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.DoregFeeInterface")
    @ResponseWrapper(localName = "doregFeeInterfaceResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.DoregFeeInterfaceResponse")
    public String doregFeeInterface(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "organdoctorId", targetNamespace = "http://tempuri.org/")
        String organdoctorId,
        @WebParam(name = "departmentorganId", targetNamespace = "http://tempuri.org/")
        String departmentorganId,
        @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
        String patientNo,
        @WebParam(name = "sourceDate", targetNamespace = "http://tempuri.org/")
        String sourceDate,
        @WebParam(name = "timestypeNo", targetNamespace = "http://tempuri.org/")
        String timestypeNo,
        @WebParam(name = "sourceTimeType", targetNamespace = "http://tempuri.org/")
        String sourceTimeType);

    /**
     * 医保挂号
     * 
     * @param synKey
     * @param synUserName
     * @param doRegIn
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doRegMedicareInfo")
    @WebResult(name = "doRegMedicareInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doRegMedicareInfo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.DoRegMedicareInfo")
    @ResponseWrapper(localName = "doRegMedicareInfoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.reg.DoRegMedicareInfoResponse")
    public String doRegMedicareInfo(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "doRegIn", targetNamespace = "http://tempuri.org/")
        String doRegIn);

}
