spring:
  profiles:
    active: dev
    include:
      - his-dev
      - terminal
  application:
    name: sip

mybatis:
  typeAliasesPackage: cn.bxd.sip.bxd.model.entity
  mapperLocations: classpath:mapper/**/*.xml
  
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  typeAliasesPackage: cn.bxd.sip.bxd.model.entity

cxf:
  path: /Client

