
package cn.bxd.sip.his.webservice.hisws.invoke;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HISInterface_qkbSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HISInterfaceQkbSoap {


    /**
     * 
     * @param synUserName
     * @param cardNo
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryPatientInfoByIdNO")
    @WebResult(name = "queryPatientInfoByIdNOResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryPatientInfoByIdNO", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryPatientInfoByIdNO")
    @ResponseWrapper(localName = "queryPatientInfoByIdNOResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryPatientInfoByIdNOResponse")
    public String queryPatientInfoByIdNO(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "cardNo", targetNamespace = "http://tempuri.org/")
                    String cardNo);

    /**
     * 
     * @param synUserName
     * @param bankCardNumber
     * @param socialsecurityNO
     * @param visitCardNo
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryPatientInfoBySocialsecurityNO")
    @WebResult(name = "queryPatientInfoBySocialsecurityNOResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryPatientInfoBySocialsecurityNO", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryPatientInfoBySocialsecurityNO")
    @ResponseWrapper(localName = "queryPatientInfoBySocialsecurityNOResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryPatientInfoBySocialsecurityNOResponse")
    public String queryPatientInfoBySocialsecurityNO(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "socialsecurityNO", targetNamespace = "http://tempuri.org/")
                    String socialsecurityNO,
            @WebParam(name = "bankCardNumber", targetNamespace = "http://tempuri.org/")
                    String bankCardNumber,
            @WebParam(name = "visitCardNo", targetNamespace = "http://tempuri.org/")
                    String visitCardNo);

    /**
     * 
     * @param synUserName
     * @param hiUser
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doCreatCardInfo")
    @WebResult(name = "doCreatCardInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doCreatCardInfo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.DoCreatCardInfo")
    @ResponseWrapper(localName = "doCreatCardInfoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.DoCreatCardInfoResponse")
    public String doCreatCardInfo(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "HiUser", targetNamespace = "http://tempuri.org/")
                    String hiUser);

    /**
     * 
     * @param reportType
     * @param synUserName
     * @param synKey
     * @param reportNos
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryExaminationRecordStatus")
    @WebResult(name = "queryExaminationRecordStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryExaminationRecordStatus", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryExaminationRecordStatus")
    @ResponseWrapper(localName = "queryExaminationRecordStatusResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryExaminationRecordStatusResponse")
    public String queryExaminationRecordStatus(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "reportNos", targetNamespace = "http://tempuri.org/")
                    String reportNos,
            @WebParam(name = "reportType", targetNamespace = "http://tempuri.org/")
                    String reportType);

    /**
     * 
     * @param reportType
     * @param synUserName
     * @param synKey
     * @param reportNos
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/updateExaminationRecordStatus")
    @WebResult(name = "updateExaminationRecordStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "updateExaminationRecordStatus", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.UpdateExaminationRecordStatus")
    @ResponseWrapper(localName = "updateExaminationRecordStatusResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.UpdateExaminationRecordStatusResponse")
    public String updateExaminationRecordStatus(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "reportNos", targetNamespace = "http://tempuri.org/")
                    String reportNos,
            @WebParam(name = "reportType", targetNamespace = "http://tempuri.org/")
                    String reportType);

    /**
     * 
     * @param synUserName
     * @param patientNo
     * @param endDate
     * @param synKey
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryExaminationRecordList")
    @WebResult(name = "queryExaminationRecordListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryExaminationRecordList", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryExaminationRecordList")
    @ResponseWrapper(localName = "queryExaminationRecordListResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryExaminationRecordListResponse")
    public String queryExaminationRecordList(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
                    String patientNo,
            @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
                    String startDate,
            @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
                    String endDate);

    /**
     * 
     * @param synUserName
     * @param patientNo
     * @param endDate
     * @param synKey
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryHisUserRecordList")
    @WebResult(name = "queryHisUserRecordListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryHisUserRecordList", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryHisUserRecordList")
    @ResponseWrapper(localName = "queryHisUserRecordListResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryHisUserRecordListResponse")
    public String queryHisUserRecordList(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
                    String patientNo,
            @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
                    String startDate,
            @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
                    String endDate);

    /**
     * 
     * @param synUserName
     * @param bankCardNumber
     * @param socialsecurityNO
     * @param visitCardNo
     * @param cardNo
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/updatePatientInfo")
    @WebResult(name = "updatePatientInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "updatePatientInfo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.UpdatePatientInfo")
    @ResponseWrapper(localName = "updatePatientInfoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.UpdatePatientInfoResponse")
    public String updatePatientInfo(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "cardNo", targetNamespace = "http://tempuri.org/")
                    String cardNo,
            @WebParam(name = "socialsecurityNO", targetNamespace = "http://tempuri.org/")
                    String socialsecurityNO,
            @WebParam(name = "bankCardNumber", targetNamespace = "http://tempuri.org/")
                    String bankCardNumber,
            @WebParam(name = "visitCardNo", targetNamespace = "http://tempuri.org/")
                    String visitCardNo);

    /**
     * 
     * @param synUserName
     * @param departmentorganId
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryDoctorList")
    @WebResult(name = "queryDoctorListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryDoctorList", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryDoctorList")
    @ResponseWrapper(localName = "queryDoctorListResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryDoctorListResponse")
    public String queryDoctorList(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "departmentorganId", targetNamespace = "http://tempuri.org/")
                    String departmentorganId);

    /**
     * 
     * @param synUserName
     * @param organId
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryDepartmentById")
    @WebResult(name = "queryDepartmentByIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryDepartmentById", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryDepartmentById")
    @ResponseWrapper(localName = "queryDepartmentByIdResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryDepartmentByIdResponse")
    public String queryDepartmentById(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "organId", targetNamespace = "http://tempuri.org/")
                    String organId);

    /**
     * 
     * @param synUserName
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryDepartmentList")
    @WebResult(name = "queryDepartmentListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryDepartmentList", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryDepartmentList")
    @ResponseWrapper(localName = "queryDepartmentListResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryDepartmentListResponse")
    public String queryDepartmentList(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey);

    /**
     * 
     * @param synUserName
     * @param organdoctorId
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryDoctorById")
    @WebResult(name = "queryDoctorByIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryDoctorById", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryDoctorById")
    @ResponseWrapper(localName = "queryDoctorByIdResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryDoctorByIdResponse")
    public String queryDoctorById(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "organdoctorId", targetNamespace = "http://tempuri.org/")
                    String organdoctorId);

    /**
     * 
     * @param synUserName
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryHospitalInfo")
    @WebResult(name = "queryHospitalInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryHospitalInfo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryHospitalInfo")
    @ResponseWrapper(localName = "queryHospitalInfoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryHospitalInfoResponse")
    public String queryHospitalInfo(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey);

    /**
     * 
     * @param synUserName
     * @param requestQty
     * @param start
     * @param type
     * @param synKey
     * @param pyCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryDrugList")
    @WebResult(name = "queryDrugListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryDrugList", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryDrugList")
    @ResponseWrapper(localName = "queryDrugListResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryDrugListResponse")
    public String queryDrugList(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "pyCode", targetNamespace = "http://tempuri.org/")
                    String pyCode,
            @WebParam(name = "Type", targetNamespace = "http://tempuri.org/")
                    String type,
            @WebParam(name = "Start", targetNamespace = "http://tempuri.org/")
                    String start,
            @WebParam(name = "RequestQty", targetNamespace = "http://tempuri.org/")
                    String requestQty);

    /**
     * 
     * @param sourceDate
     * @param synUserName
     * @param patientNo
     * @param sourceMark
     * @param departmentorganId
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doRegCancel")
    @WebResult(name = "doRegCancelResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doRegCancel", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.DoRegCancel")
    @ResponseWrapper(localName = "doRegCancelResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.DoRegCancelResponse")
    public String doRegCancel(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "sourceMark", targetNamespace = "http://tempuri.org/")
                    String sourceMark,
            @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
                    String patientNo,
            @WebParam(name = "sourceDate", targetNamespace = "http://tempuri.org/")
                    String sourceDate,
            @WebParam(name = "departmentorganId", targetNamespace = "http://tempuri.org/")
                    String departmentorganId);

    /**
     * 
     * @param synUserName
     * @param doRegIn
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doReg")
    @WebResult(name = "doRegResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doReg", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.DoReg")
    @ResponseWrapper(localName = "doRegResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.DoRegResponse")
    public String doReg(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "doRegIn", targetNamespace = "http://tempuri.org/")
                    String doRegIn);

    /**
     * 
     * @param synUserName
     * @param endDate
     * @param synKey
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryToRegDoctorList")
    @WebResult(name = "queryToRegDoctorListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryToRegDoctorList", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryToRegDoctorList")
    @ResponseWrapper(localName = "queryToRegDoctorListResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryToRegDoctorListResponse")
    public String queryToRegDoctorList(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
                    String startDate,
            @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
                    String endDate);

    /**
     * 
     * @param synUserName
     * @param organdoctorId
     * @param endDate
     * @param synKey
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryToRegDoctorListByDoctorId")
    @WebResult(name = "queryToRegDoctorListByDoctorIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryToRegDoctorListByDoctorId", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryToRegDoctorListByDoctorId")
    @ResponseWrapper(localName = "queryToRegDoctorListByDoctorIdResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryToRegDoctorListByDoctorIdResponse")
    public String queryToRegDoctorListByDoctorId(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
                    String startDate,
            @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
                    String endDate,
            @WebParam(name = "organdoctorId", targetNamespace = "http://tempuri.org/")
                    String organdoctorId);

    /**
     * 
     * @param sourceDate
     * @param synUserName
     * @param patientNo
     * @param sourceMark
     * @param departmentorganId
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryRegWaitNum")
    @WebResult(name = "queryRegWaitNumResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryRegWaitNum", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryRegWaitNum")
    @ResponseWrapper(localName = "queryRegWaitNumResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryRegWaitNumResponse")
    public String queryRegWaitNum(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "sourceMark", targetNamespace = "http://tempuri.org/")
                    String sourceMark,
            @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
                    String patientNo,
            @WebParam(name = "sourceDate", targetNamespace = "http://tempuri.org/")
                    String sourceDate,
            @WebParam(name = "departmentorganId", targetNamespace = "http://tempuri.org/")
                    String departmentorganId);

    /**
     * 
     * @param sourceDate
     * @param synUserName
     * @param patientNo
     * @param sourceMark
     * @param departmentorganId
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryTaketheNo")
    @WebResult(name = "queryTaketheNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryTaketheNo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryTaketheNo")
    @ResponseWrapper(localName = "queryTaketheNoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryTaketheNoResponse")
    public String queryTaketheNo(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "sourceMark", targetNamespace = "http://tempuri.org/")
                    String sourceMark,
            @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
                    String patientNo,
            @WebParam(name = "sourceDate", targetNamespace = "http://tempuri.org/")
                    String sourceDate,
            @WebParam(name = "departmentorganId", targetNamespace = "http://tempuri.org/")
                    String departmentorganId);

    /**
     * @Param synUserName               用户名
     * @Param synKey                效验码
     * @Param terminalCode                  终端编号
     * @Param hospitalId                医院ID
     * @Param sourceMark                号源编号
     * @Param patientNo                 患者编号
     * @Param sourceDate                号源日期
     * @Param departmentorganId                 科室编号
     * @Param payType               1,银联，2支付宝 3，现场支付 4、医保账户，5、微信，6、建行，7、中行
     * @Param payRecord                 支付交易流水号
     * @Param payMoney                  实际支付金额
     * @Param extend                扩展字段Json值，如：{“key1”：”value1” ，”key2”：”value2”}     * 支付宝微信医保支付这里要传订单号（poNo）
     * @Author cRyann
     * @Create 2018/9/12
     * @Description 1.5.7    门诊取号
     */
    @WebMethod(action = "http://tempuri.org/doTaketheNo")
    @WebResult(name = "doTaketheNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doTaketheNo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.DoTaketheNo")
    @ResponseWrapper(localName = "doTaketheNoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.DoTaketheNoResponse")
    public String doTaketheNo(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "sourceMark", targetNamespace = "http://tempuri.org/")
                    String sourceMark,
            @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
                    String patientNo,
            @WebParam(name = "sourceDate", targetNamespace = "http://tempuri.org/")
                    String sourceDate,
            @WebParam(name = "departmentorganId", targetNamespace = "http://tempuri.org/")
                    String departmentorganId,
            @WebParam(name = "payType", targetNamespace = "http://tempuri.org/")
                    String payType,
            @WebParam(name = "payRecord", targetNamespace = "http://tempuri.org/")
                    String payRecord,
            @WebParam(name = "payMoney", targetNamespace = "http://tempuri.org/")
                    String payMoney);
    /**
     * 
     * @param synUserName
     * @param doRegIn
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doRegAndTaketheNo")
    @WebResult(name = "doRegAndTaketheNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doRegAndTaketheNo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.DoRegAndTaketheNo")
    @ResponseWrapper(localName = "doRegAndTaketheNoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.DoRegAndTaketheNoResponse")
    public String doRegAndTaketheNo(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "doRegIn", targetNamespace = "http://tempuri.org/")
                    String doRegIn);

    /**
     * 
     * @param synUserName
     * @param patientNo
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryRegBypatientNo")
    @WebResult(name = "queryRegBypatientNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryRegBypatientNo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryRegBypatientNo")
    @ResponseWrapper(localName = "queryRegBypatientNoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryRegBypatientNoResponse")
    public String queryRegBypatientNo(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
                    String patientNo);

    /**
     * 
     * @param sourceDate
     * @param synUserName
     * @param organdoctorId
     * @param sourceTimeType
     * @param departmentorganId
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryToRegDoctorTimes")
    @WebResult(name = "queryToRegDoctorTimesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryToRegDoctorTimes", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryToRegDoctorTimes")
    @ResponseWrapper(localName = "queryToRegDoctorTimesResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryToRegDoctorTimesResponse")
    public String queryToRegDoctorTimes(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "sourceDate", targetNamespace = "http://tempuri.org/")
                    String sourceDate,
            @WebParam(name = "organdoctorId", targetNamespace = "http://tempuri.org/")
                    String organdoctorId,
            @WebParam(name = "departmentorganId", targetNamespace = "http://tempuri.org/")
                    String departmentorganId,
            @WebParam(name = "sourceTimeType", targetNamespace = "http://tempuri.org/")
                    String sourceTimeType);

    /**
     * 
     * @param synUserName
     * @param sourceMark
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryAppointmentPayStatus")
    @WebResult(name = "queryAppointmentPayStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryAppointmentPayStatus", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryAppointmentPayStatus")
    @ResponseWrapper(localName = "queryAppointmentPayStatusResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryAppointmentPayStatusResponse")
    public String queryAppointmentPayStatus(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "sourceMark", targetNamespace = "http://tempuri.org/")
                    String sourceMark);

    /**
     * 
     * @param synUserName
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doctorStopped")
    @WebResult(name = "doctorStoppedResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doctorStopped", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.DoctorStopped")
    @ResponseWrapper(localName = "doctorStoppedResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.DoctorStoppedResponse")
    public String doctorStopped(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey);

    /**
     *  1.3.4	查询挂号费
     *
     * @param sourcetimetype
     * @param synkey
     * @param synusername
     * @param organdoctorid
     * @param patientno
     * @param timestypeno
     * @param sourcedate
     * @param departmentorganid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doregFeeInterface")
    @WebResult(name = "doregFeeInterfaceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doregFeeInterface", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.DoregFeeInterface")
    @ResponseWrapper(localName = "doregFeeInterfaceResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.DoregFeeInterfaceResponse")
    public String doregFeeInterface(
            @WebParam(name = "synusername", targetNamespace = "http://tempuri.org/")
                    String synusername,
            @WebParam(name = "synkey", targetNamespace = "http://tempuri.org/")
                    String synkey,
            @WebParam(name = "organdoctorid", targetNamespace = "http://tempuri.org/")
                    String organdoctorid,
            @WebParam(name = "departmentorganid", targetNamespace = "http://tempuri.org/")
                    String departmentorganid,
            @WebParam(name = "patientno", targetNamespace = "http://tempuri.org/")
                    String patientno,
            @WebParam(name = "sourcedate", targetNamespace = "http://tempuri.org/")
                    String sourcedate,
            @WebParam(name = "timestypeno", targetNamespace = "http://tempuri.org/")
                    String timestypeno,
            @WebParam(name = "sourcetimetype", targetNamespace = "http://tempuri.org/")
                    String sourcetimetype);


    /**
     * 
     * @param synUserName
     * @param organdoctorId
     * @param departmentorganId
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryDoctorRegWaitNum")
    @WebResult(name = "queryDoctorRegWaitNumResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryDoctorRegWaitNum", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryDoctorRegWaitNum")
    @ResponseWrapper(localName = "queryDoctorRegWaitNumResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryDoctorRegWaitNumResponse")
    public String queryDoctorRegWaitNum(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "organdoctorId", targetNamespace = "http://tempuri.org/")
                    String organdoctorId,
            @WebParam(name = "departmentorganId", targetNamespace = "http://tempuri.org/")
                    String departmentorganId);

    /**
     * 
     * @param synUserName
     * @param doRegIn
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doRegMedicareInfo")
    @WebResult(name = "doRegMedicareInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doRegMedicareInfo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.DoRegMedicareInfo")
    @ResponseWrapper(localName = "doRegMedicareInfoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.DoRegMedicareInfoResponse")
    public String doRegMedicareInfo(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "doRegIn", targetNamespace = "http://tempuri.org/")
                    String doRegIn);

    /**
     * 
     * @param synUserName
     * @param patientNo
     * @param medicareType
     * @param medicareMess
     * @param terminalCode
     * @param synKey
     * @param terminalType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryToPayRecipeInfoList")
    @WebResult(name = "queryToPayRecipeInfoListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryToPayRecipeInfoList", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryToPayRecipeInfoListRes")
    @ResponseWrapper(localName = "queryToPayRecipeInfoListResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryToPayRecipeInfoListResponse")
    public String queryToPayRecipeInfoList(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
                    String patientNo,
            @WebParam(name = "medicareType", targetNamespace = "http://tempuri.org/")
                    String medicareType,
            @WebParam(name = "medicareMess", targetNamespace = "http://tempuri.org/")
                    String medicareMess,
            @WebParam(name = "terminalCode", targetNamespace = "http://tempuri.org/")
                    String terminalCode,
            @WebParam(name = "terminalType", targetNamespace = "http://tempuri.org/")
                    String terminalType);

    /**
     * 
     * @param synUserName
     * @param patientNo
     * @param endDate
     * @param synKey
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryPaymentRecordList")
    @WebResult(name = "queryPaymentRecordListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryPaymentRecordList", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryPaymentRecordList")
    @ResponseWrapper(localName = "queryPaymentRecordListResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryPaymentRecordListResponse")
    public String queryPaymentRecordList(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
                    String patientNo,
            @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
                    String startDate,
            @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
                    String endDate);

    /**
     * 
     * @param synUserName
     * @param payType
     * @param payMoney
     * @param payRecord
     * @param hiFeeNos
     * @param socialsecurityNO
     * @param overMoney
     * @param medicareMoney
     * @param synKey
     * @param overRecord
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryPayStatus")
    @WebResult(name = "queryPayStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryPayStatus", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryPayStatus")
    @ResponseWrapper(localName = "queryPayStatusResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryPayStatusResponse")
    public String queryPayStatus(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "hiFeeNos", targetNamespace = "http://tempuri.org/")
                    String hiFeeNos,
            @WebParam(name = "payType", targetNamespace = "http://tempuri.org/")
                    String payType,
            @WebParam(name = "payRecord", targetNamespace = "http://tempuri.org/")
                    String payRecord,
            @WebParam(name = "payMoney", targetNamespace = "http://tempuri.org/")
                    String payMoney,
            @WebParam(name = "medicareMoney", targetNamespace = "http://tempuri.org/")
                    String medicareMoney,
            @WebParam(name = "socialsecurityNO", targetNamespace = "http://tempuri.org/")
                    String socialsecurityNO,
            @WebParam(name = "overRecord", targetNamespace = "http://tempuri.org/")
                    String overRecord,
            @WebParam(name = "overMoney", targetNamespace = "http://tempuri.org/")
                    String overMoney);

    /**
     * 
     * @param synUserName
     * @param patientNo
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryInvoiceReportList")
    @WebResult(name = "queryInvoiceReportListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryInvoiceReportList", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryInvoiceReportList")
    @ResponseWrapper(localName = "queryInvoiceReportListResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryInvoiceReportListResponse")
    public String queryInvoiceReportList(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
                    String patientNo);

    /**
     * 
     * @param synUserName
     * @param outInvoiceId
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryInvoiceDetail")
    @WebResult(name = "queryInvoiceDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryInvoiceDetail", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryInvoiceDetail")
    @ResponseWrapper(localName = "queryInvoiceDetailResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryInvoiceDetailResponse")
    public String queryInvoiceDetail(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "outInvoiceId", targetNamespace = "http://tempuri.org/")
                    String outInvoiceId);

    /**
     * 
     * @param synUserName
     * @param clinicTrueNo
     * @param visitCardNo
     * @param cardTypeID
     * @param terminalCode
     * @param outInvoiceId
     * @param cardNo
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/updateInvoiceStatus")
    @WebResult(name = "updateInvoiceStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "updateInvoiceStatus", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.UpdateInvoiceStatus")
    @ResponseWrapper(localName = "updateInvoiceStatusResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.UpdateInvoiceStatusResponse")
    public String updateInvoiceStatus(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "outInvoiceId", targetNamespace = "http://tempuri.org/")
                    String outInvoiceId,
            @WebParam(name = "clinicTrueNo", targetNamespace = "http://tempuri.org/")
                    String clinicTrueNo,
            @WebParam(name = "cardTypeID", targetNamespace = "http://tempuri.org/")
                    String cardTypeID,
            @WebParam(name = "cardNo", targetNamespace = "http://tempuri.org/")
                    String cardNo,
            @WebParam(name = "visitCardNo", targetNamespace = "http://tempuri.org/")
                    String visitCardNo,
            @WebParam(name = "terminalCode", targetNamespace = "http://tempuri.org/")
                    String terminalCode);

    /**
     * 
     * @param payRecord
     * @param socialsecurityNO
     * @param userNo
     * @param overMoney
     * @param medicareReturn
     * @param synKey
     * @param overRecord
     * @param synUserName
     * @param payType
     * @param payMoney
     * @param bankReturn
     * @param hiFeeNos
     * @param medicareType
     * @param terminalCode
     * @param medicareMoney
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doPay")
    @WebResult(name = "doPayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doPay", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.DoPay")
    @ResponseWrapper(localName = "doPayResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.DoPayResponse")
    public String doPay(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "hiFeeNos", targetNamespace = "http://tempuri.org/")
                    String hiFeeNos,
            @WebParam(name = "payType", targetNamespace = "http://tempuri.org/")
                    String payType,
            @WebParam(name = "payRecord", targetNamespace = "http://tempuri.org/")
                    String payRecord,
            @WebParam(name = "payMoney", targetNamespace = "http://tempuri.org/")
                    String payMoney,
            @WebParam(name = "medicareMoney", targetNamespace = "http://tempuri.org/")
                    String medicareMoney,
            @WebParam(name = "socialsecurityNO", targetNamespace = "http://tempuri.org/")
                    String socialsecurityNO,
            @WebParam(name = "overRecord", targetNamespace = "http://tempuri.org/")
                    String overRecord,
            @WebParam(name = "overMoney", targetNamespace = "http://tempuri.org/")
                    String overMoney,
            @WebParam(name = "medicareReturn", targetNamespace = "http://tempuri.org/")
                    String medicareReturn,
            @WebParam(name = "bankReturn", targetNamespace = "http://tempuri.org/")
                    String bankReturn,
            @WebParam(name = "terminalCode", targetNamespace = "http://tempuri.org/")
                    String terminalCode,
            @WebParam(name = "userNo", targetNamespace = "http://tempuri.org/")
                    String userNo,
            @WebParam(name = "medicareType", targetNamespace = "http://tempuri.org/")
                    String medicareType);

    /**
     * 
     * @param synUserName
     * @param hiFeeNos
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/updateRecipeStatusStatus")
    @WebResult(name = "updateRecipeStatusStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "updateRecipeStatusStatus", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.UpdateRecipeStatusStatus")
    @ResponseWrapper(localName = "updateRecipeStatusStatusResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.UpdateRecipeStatusStatusResponse")
    public String updateRecipeStatusStatus(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "hiFeeNos", targetNamespace = "http://tempuri.org/")
                    String hiFeeNos);

    /**
     * 
     * @param synUserName
     * @param payType
     * @param payMoney
     * @param inHosNo
     * @param bedNo
     * @param payRecord
     * @param terminalCode
     * @param synKey
     * @param payReturn
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/inpatientPayment")
    @WebResult(name = "inpatientPaymentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "inpatientPayment", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.InpatientPayment")
    @ResponseWrapper(localName = "inpatientPaymentResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.InpatientPaymentResponse")
    public String inpatientPayment(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "inHosNo", targetNamespace = "http://tempuri.org/")
                    String inHosNo,
            @WebParam(name = "bedNo", targetNamespace = "http://tempuri.org/")
                    String bedNo,
            @WebParam(name = "payType", targetNamespace = "http://tempuri.org/")
                    String payType,
            @WebParam(name = "payRecord", targetNamespace = "http://tempuri.org/")
                    String payRecord,
            @WebParam(name = "payMoney", targetNamespace = "http://tempuri.org/")
                    String payMoney,
            @WebParam(name = "payReturn", targetNamespace = "http://tempuri.org/")
                    String payReturn,
            @WebParam(name = "terminalCode", targetNamespace = "http://tempuri.org/")
                    String terminalCode);

    /**
     * 
     * @param synUserName
     * @param patientNo
     * @param endDate
     * @param inHosNo
     * @param synKey
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/payDetail")
    @WebResult(name = "payDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "payDetail", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.PayDetail")
    @ResponseWrapper(localName = "payDetailResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.PayDetailResponse")
    public String payDetail(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
                    String patientNo,
            @WebParam(name = "inHosNo", targetNamespace = "http://tempuri.org/")
                    String inHosNo,
            @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
                    String startDate,
            @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
                    String endDate);

    /**
     * 
     * @param synUserName
     * @param patientNo
     * @param endDate
     * @param inHosNo
     * @param synKey
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/inHosDetail")
    @WebResult(name = "inHosDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "inHosDetail", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.InHosDetail")
    @ResponseWrapper(localName = "inHosDetailResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.InHosDetailResponse")
    public String inHosDetail(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
                    String patientNo,
            @WebParam(name = "inHosNo", targetNamespace = "http://tempuri.org/")
                    String inHosNo,
            @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
                    String startDate,
            @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
                    String endDate);

    /**
     * 
     * @param synUserName
     * @param inHosNo
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryLeaveHosDetail")
    @WebResult(name = "queryLeaveHosDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryLeaveHosDetail", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryLeaveHosDetail")
    @ResponseWrapper(localName = "queryLeaveHosDetailResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryLeaveHosDetailResponse")
    public String queryLeaveHosDetail(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "inHosNo", targetNamespace = "http://tempuri.org/")
                    String inHosNo);

    /**
     * 
     * @param synUserName
     * @param bankCardNumber
     * @param socialsecurityNO
     * @param visitCardNo
     * @param cardNo
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryPatientInHosInfo")
    @WebResult(name = "queryPatientInHosInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryPatientInHosInfo", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryPatientInHosInfo")
    @ResponseWrapper(localName = "queryPatientInHosInfoResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryPatientInHosInfoResponse")
    public String queryPatientInHosInfo(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "cardNo", targetNamespace = "http://tempuri.org/")
                    String cardNo,
            @WebParam(name = "visitCardNo", targetNamespace = "http://tempuri.org/")
                    String visitCardNo,
            @WebParam(name = "socialsecurityNO", targetNamespace = "http://tempuri.org/")
                    String socialsecurityNO,
            @WebParam(name = "bankCardNumber", targetNamespace = "http://tempuri.org/")
                    String bankCardNumber);

    /**
     * 
     * @param synUserName
     * @param inHosNo
     * @param bedNo
     * @param departmentorganId
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryArrears")
    @WebResult(name = "queryArrearsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryArrears", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryArrears")
    @ResponseWrapper(localName = "queryArrearsResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.QueryArrearsResponse")
    public String queryArrears(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "inHosNo", targetNamespace = "http://tempuri.org/")
                    String inHosNo,
            @WebParam(name = "bedNo", targetNamespace = "http://tempuri.org/")
                    String bedNo,
            @WebParam(name = "departmentorganId", targetNamespace = "http://tempuri.org/")
                    String departmentorganId);
    
    @WebMethod(action = "http://tempuri.org/updateRecipeRecordStatus")
    @WebResult(name = "updateRecipeRecordStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "updateRecipeRecordStatus", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.UpdateRecipeRecordStatus")
    @ResponseWrapper(localName = "updateRecipeRecordStatusResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.UpdateRecipeRecordStatusResponse")
    public String updateRecipeRecordStatus(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "hiFeeNos", targetNamespace = "http://tempuri.org/")
                    String hiFeeNos,
            @WebParam(name = "extend", targetNamespace = "http://tempuri.org/")
                    String extend);
    
    
    @WebMethod(action = "http://tempuri.org/updateInHosRecordStatus")
    @WebResult(name = "updateInHosRecordStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "updateInHosRecordStatus", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.UpdateInHosRecordStatus")
    @ResponseWrapper(localName = "updateInHosRecordStatusResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke.UpdateInHosRecordStatusResponse")
    public String updateInHosRecordStatus(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "inHosNo", targetNamespace = "http://tempuri.org/")
                    String inHosNo,
            @WebParam(name = "recordDate", targetNamespace = "http://tempuri.org/")
                    String recordDate,
            @WebParam(name = "recordType", targetNamespace = "http://tempuri.org/")
                    String recordType,
            @WebParam(name = "extend", targetNamespace = "http://tempuri.org/")
                    String extend);

}
