
package cn.bxd.sip.his.webservice.hisws.invoke;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "RegSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface RegSoap {


    /**
     *  1.3.1取消预约
     *
     * @param sourceDate
     * @param synUserName
     * @param patientNo
     * @param sourceMark
     * @param departmentorganId
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doRegCancel")
    @WebResult(name = "doRegCancelResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doRegCancel", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.DoRegCancel")
    @ResponseWrapper(localName = "doRegCancelResponse", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.DoRegCancelResponse")
    public String doRegCancel(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "sourceMark", targetNamespace = "http://tempuri.org/")
                    String sourceMark,
            @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
                    String patientNo,
            @WebParam(name = "sourceDate", targetNamespace = "http://tempuri.org/")
                    String sourceDate,
            @WebParam(name = "departmentorganId", targetNamespace = "http://tempuri.org/")
                    String departmentorganId);

    /**
     *  1.3.2预约挂号
     *
     * @param synUserName
     * @param doRegIn
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doReg")
    @WebResult(name = "doRegResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doReg", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.DoReg")
    @ResponseWrapper(localName = "doRegResponse", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.DoRegResponse")
    public String doReg(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "doRegIn", targetNamespace = "http://tempuri.org/")
                    String doRegIn);

    /**
     *  1.3.3查询号源
     *
     * @param synUserName
     * @param endDate
     * @param synKey
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryToRegDoctorList")
    @WebResult(name = "queryToRegDoctorListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryToRegDoctorList", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.GetQueueListOperation")
    @ResponseWrapper(localName = "queryToRegDoctorListResponse", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.QueryToRegDoctorListResponse")
    public String queryToRegDoctorList(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
                    String startDate,
            @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
                    String endDate);

    /**
     *  1.3.4根据医生查询号源
     *
     * @param synUserName
     * @param endDate
     * @param doctorID
     * @param synKey
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryToRegDoctorListByDoctorId")
    @WebResult(name = "queryToRegDoctorListByDoctorIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryToRegDoctorListByDoctorId", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.QueryToRegDoctorListByDoctorId")
    @ResponseWrapper(localName = "queryToRegDoctorListByDoctorIdResponse", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.QueryToRegDoctorListByDoctorIdResponse")
    public String queryToRegDoctorListByDoctorId(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
                    String startDate,
            @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
                    String endDate,
            @WebParam(name = "doctorID", targetNamespace = "http://tempuri.org/")
                    String doctorID);

    /**
     *  1.3.5排取人数
     *
     * @param sourceDate
     * @param synUserName
     * @param patientNo
     * @param sourceMark
     * @param departmentorganId
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryRegWaitNum")
    @WebResult(name = "queryRegWaitNumResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryRegWaitNum", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.QueryRegWaitNum")
    @ResponseWrapper(localName = "queryRegWaitNumResponse", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.QueryRegWaitNumResponse")
    public String queryRegWaitNum(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "sourceMark", targetNamespace = "http://tempuri.org/")
                    String sourceMark,
            @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
                    String patientNo,
            @WebParam(name = "sourceDate", targetNamespace = "http://tempuri.org/")
                    String sourceDate,
            @WebParam(name = "departmentorganId", targetNamespace = "http://tempuri.org/")
                    String departmentorganId);

    /**
     *  1.3.6取号查询接口
     *
     * @param sourceDate
     * @param synUserName
     * @param patientNo
     * @param sourceMark
     * @param departmentorganId
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryTaketheNo")
    @WebResult(name = "queryTaketheNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryTaketheNo", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.QueryTaketheNo")
    @ResponseWrapper(localName = "queryTaketheNoResponse", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.QueryTaketheNoResponse")
    public String queryTaketheNo(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "sourceMark", targetNamespace = "http://tempuri.org/")
                    String sourceMark,
            @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
                    String patientNo,
            @WebParam(name = "sourceDate", targetNamespace = "http://tempuri.org/")
                    String sourceDate,
            @WebParam(name = "departmentorganId", targetNamespace = "http://tempuri.org/")
                    String departmentorganId);

    /**
     *  1.3.7门诊取号
     *
     * @param synUserName
     * @param synKey
     * @param doTakeIn
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doTaketheNo")
    @WebResult(name = "doTaketheNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doTaketheNo", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.DoTaketheNo")
    @ResponseWrapper(localName = "doTaketheNoResponse", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.DoTaketheNoResponse")
    public String doTaketheNo(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "doTakeIn", targetNamespace = "http://tempuri.org/")
                    String doTakeIn);

    /**
     *  1.3.8预约当天并取号
     *
     * @param synUserName
     * @param doRegIn
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doRegAndTaketheNo")
    @WebResult(name = "doRegAndTaketheNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doRegAndTaketheNo", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.DoRegAndTaketheNo")
    @ResponseWrapper(localName = "doRegAndTaketheNoResponse", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.DoRegAndTaketheNoResponse")
    public String doRegAndTaketheNo(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "DoRegIn", targetNamespace = "http://tempuri.org/")
                    String doRegIn);

    /**
     *  1.3.9查询未取号的预约挂号
     *
     * @param synUserName
     * @param patientNo
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryRegBypatientNo")
    @WebResult(name = "queryRegBypatientNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryRegBypatientNo", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.QueryRegBypatientNo")
    @ResponseWrapper(localName = "queryRegBypatientNoResponse", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.QueryRegBypatientNoResponse")
    public String queryRegBypatientNo(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
                    String patientNo);

    /**
     *  1.3.10查询医生号源时间段
     *
     * @param sourceDate
     * @param synUserName
     * @param organdoctorId
     * @param sourceTimeType
     * @param departmentorganId
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryToRegDoctorTimes")
    @WebResult(name = "queryToRegDoctorTimesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryToRegDoctorTimes", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.QueryToRegDoctorTimes")
    @ResponseWrapper(localName = "queryToRegDoctorTimesResponse", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.QueryToRegDoctorTimesResponse")
    public String queryToRegDoctorTimes(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "sourceDate", targetNamespace = "http://tempuri.org/")
                    String sourceDate,
            @WebParam(name = "organdoctorId", targetNamespace = "http://tempuri.org/")
                    String organdoctorId,
            @WebParam(name = "departmentorganId", targetNamespace = "http://tempuri.org/")
                    String departmentorganId,
            @WebParam(name = "sourceTimeType", targetNamespace = "http://tempuri.org/")
                    String sourceTimeType);

    /**
     *  1.3.11查询挂号支付状态
     *
     * @param synUserName
     * @param sourceMark
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryAppointmentPayStatus")
    @WebResult(name = "queryAppointmentPayStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryAppointmentPayStatus", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.QueryAppointmentPayStatus")
    @ResponseWrapper(localName = "queryAppointmentPayStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.QueryAppointmentPayStatusResponse")
    public String queryAppointmentPayStatus(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "sourceMark", targetNamespace = "http://tempuri.org/")
                    String sourceMark);

    /**
     *  1.3.12医生停诊
     *
     * @param synUserName
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doctorStopped")
    @WebResult(name = "doctorStoppedResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doctorStopped", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.DoctorStopped")
    @ResponseWrapper(localName = "doctorStoppedResponse", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.DoctorStoppedResponse")
    public String doctorStopped(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey);

    /**
     *  1.3.13查询医生当前排队人数
     *
     * @param synUserName
     * @param organdoctorId
     * @param departmentorganId
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryDoctorRegWaitNum")
    @WebResult(name = "queryDoctorRegWaitNumResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryDoctorRegWaitNum", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.QueryDoctorRegWaitNum")
    @ResponseWrapper(localName = "queryDoctorRegWaitNumResponse", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.QueryDoctorRegWaitNumResponse")
    public String queryDoctorRegWaitNum(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "organdoctorId", targetNamespace = "http://tempuri.org/")
                    String organdoctorId,
            @WebParam(name = "departmentorganId", targetNamespace = "http://tempuri.org/")
                    String departmentorganId);

    /**
     *  1.3.14平台医生停诊
     *
     * @param synUserName
     * @param stopList
     * @param hospitalId
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/stopworking")
    @WebResult(name = "stopworkingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "stopworking", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.Stopworking")
    @ResponseWrapper(localName = "stopworkingResponse", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.StopworkingResponse")
    public String stopworking(
            @WebParam(name = "hospitalId", targetNamespace = "http://tempuri.org/")
                    String hospitalId,
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "stopList", targetNamespace = "http://tempuri.org/")
                    String stopList);

    /**
     *  1.3.15查询挂号费
     *
     * @param sourceDate
     * @param synUserName
     * @param organdoctorId
     * @param patientNo
     * @param timestypeNo
     * @param sourceTimeType
     * @param departmentorganId
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doregFeeInterface")
    @WebResult(name = "doregFeeInterfaceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doregFeeInterface", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.DoregFeeInterface")
    @ResponseWrapper(localName = "doregFeeInterfaceResponse", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.DoregFeeInterfaceResponse")
    public String doregFeeInterface(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "organdoctorId", targetNamespace = "http://tempuri.org/")
                    String organdoctorId,
            @WebParam(name = "departmentorganId", targetNamespace = "http://tempuri.org/")
                    String departmentorganId,
            @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
                    String patientNo,
            @WebParam(name = "sourceDate", targetNamespace = "http://tempuri.org/")
                    String sourceDate,
            @WebParam(name = "timestypeNo", targetNamespace = "http://tempuri.org/")
                    String timestypeNo,
            @WebParam(name = "sourceTimeType", targetNamespace = "http://tempuri.org/")
                    String sourceTimeType);

    /**
     *  1.3.16获取挂号医保信息
     *
     * @param synUserName
     * @param doRegIn
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doRegMedicareInfo")
    @WebResult(name = "doRegMedicareInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doRegMedicareInfo", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.DoRegMedicareInfo")
    @ResponseWrapper(localName = "doRegMedicareInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.DoRegMedicareInfoResponse")
    public String doRegMedicareInfo(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "doRegIn", targetNamespace = "http://tempuri.org/")
                    String doRegIn);

    /**
     *  1.3.17号源锁号
     *
     * @param sourceDate
     * @param synUserName
     * @param patientNO
     * @param proCode
     * @param hospitalId
     * @param timestypeNo
     * @param terminalCode
     * @param cardNo
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/lockRegisterNo")
    @WebResult(name = "lockRegisterNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "lockRegisterNo", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.LockRegisterNo")
    @ResponseWrapper(localName = "lockRegisterNoResponse", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.his.LockRegisterNoResponse")
    public String lockRegisterNo(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "terminalCode", targetNamespace = "http://tempuri.org/")
                    String terminalCode,
            @WebParam(name = "hospitalId", targetNamespace = "http://tempuri.org/")
                    String hospitalId,
            @WebParam(name = "patientNO", targetNamespace = "http://tempuri.org/")
                    String patientNO,
            @WebParam(name = "proCode", targetNamespace = "http://tempuri.org/")
                    String proCode,
            @WebParam(name = "cardNo", targetNamespace = "http://tempuri.org/")
                    String cardNo,
            @WebParam(name = "timestypeNo", targetNamespace = "http://tempuri.org/")
                    String timestypeNo,
            @WebParam(name = "sourceDate", targetNamespace = "http://tempuri.org/")
                    String sourceDate);

}
