
package cn.bxd.sip.his.webservice.hisws.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RegSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RegSoap {


    /**
     *  1.3.3	查询号源(必选)
     * 
     * @param synUserName
     * @param endDate
     * @param synKey
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryToRegDoctorList")
    @WebResult(name = "queryToRegDoctorListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryToRegDoctorList", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.test.QueryToRegDoctorList")
    @ResponseWrapper(localName = "queryToRegDoctorListResponse", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.test.QueryToRegDoctorListResponse")
    public String queryToRegDoctorList(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
                    String startDate,
            @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
                    String endDate);

    /**
     *  1.3.4	根据医生ID查询号源(必选)
     * 
     * @param synUserName
     * @param organdoctorId
     * @param endDate
     * @param synKey
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryToRegDoctorListByDoctorId")
    @WebResult(name = "queryToRegDoctorListByDoctorIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryToRegDoctorListByDoctorId", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.test.QueryToRegDoctorListByDoctorId")
    @ResponseWrapper(localName = "queryToRegDoctorListByDoctorIdResponse", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.test.QueryToRegDoctorListByDoctorIdResponse")
    public String queryToRegDoctorListByDoctorId(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
                    String startDate,
            @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
                    String endDate,
            @WebParam(name = "organdoctorId", targetNamespace = "http://tempuri.org/")
                    String organdoctorId);

    /**
     *  1.3.10	查询医生号源时间段（必选）
     * 
     * @param sourceDate
     * @param synUserName
     * @param organdoctorId
     * @param sourceTimeType
     * @param departmentorganId
     * @param synKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryToRegDoctorTimes")
    @WebResult(name = "queryToRegDoctorTimesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryToRegDoctorTimes", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.test.QueryToRegDoctorTimes")
    @ResponseWrapper(localName = "queryToRegDoctorTimesResponse", targetNamespace = "http://tempuri.org/", className = "com.bxd.hisws.test.QueryToRegDoctorTimesResponse")
    public String queryToRegDoctorTimes(
            @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
                    String synKey,
            @WebParam(name = "sourceDate", targetNamespace = "http://tempuri.org/")
                    String sourceDate,
            @WebParam(name = "organdoctorId", targetNamespace = "http://tempuri.org/")
                    String organdoctorId,
            @WebParam(name = "departmentorganId", targetNamespace = "http://tempuri.org/")
                    String departmentorganId,
            @WebParam(name = "sourceTimeType", targetNamespace = "http://tempuri.org/")
                    String sourceTimeType);

}
