
package cn.bxd.sip.bxd.webservice.invoke.hisUser;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebService(name = "TIHisUser", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface TIHisUser {

    /**
     * @param synUserName  用户名
     * @param synKey       效验码
     * @param terminalCode 终端编号
     * @param hospitalId   医院ID
     * @param mobileNo     手机号码
     * @Description 1.2.1    获取验证码
     * returns cn.bxd.sip.bxd.webservice.invoke.hisUser.TGetSMSCodeRespond
     */
    @WebMethod(action = "http://webservice.bxd.sip.bxd.cn/getSMSCode")
    @WebResult(name = "getSMSCodeResult", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
    @RequestWrapper(localName = "getSMSCode", targetNamespace = "http://webservice.bxd.sip.bxd.cn/", className = "cn.bxd.sip.bxd.webservice.invoke.hisUser.TGetSMSCode")
    @ResponseWrapper(localName = "getSMSCodeResponse", targetNamespace = "http://webservice.bxd.sip.bxd.cn/", className = "cn.bxd.sip.bxd.webservice.invoke.hisUser.TGetSMSCodeResponse")
    public TGetSMSCodeRespond getSMSCode(
            @WebParam(name = "synUserName", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String synKey,
            @WebParam(name = "terminalCode", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String terminalCode,
            @WebParam(name = "hospitalId", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String hospitalId,
            @WebParam(name = "mobileNo", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String mobileNo);

    /**
     * @param synUserName         用户名
     * @param synKey              效验码
     * @param terminalCode        终端编号
     * @param hospitalId          医院ID
     * @param mobileNo            手机号码
     * @param password            密码
     * @param socialsecurityNO    医保号
     * @Description 1.2.2    已注册判断手机号码和社保卡是否绑定
     * @return returns cn.bxd.sip.bxd.webservice.invoke.hisUser.TRegisteredConfirmsExistRespond
     */
    @WebMethod(action = "http://webservice.bxd.sip.bxd.cn/registeredConfirmsExist")
    @WebResult(name = "registeredConfirmsExistResult", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
    @RequestWrapper(localName = "registeredConfirmsExist", targetNamespace = "http://webservice.bxd.sip.bxd.cn/", className = "cn.bxd.sip.bxd.webservice.invoke.hisUser.TRegisteredConfirmsExist")
    @ResponseWrapper(localName = "registeredConfirmsExistResponse", targetNamespace = "http://webservice.bxd.sip.bxd.cn/", className = "cn.bxd.sip.bxd.webservice.invoke.hisUser.TRegisteredConfirmsExistResponse")
    public TRegisteredConfirmsExistRespond registeredConfirmsExist(
            @WebParam(name = "synUserName", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String synKey,
            @WebParam(name = "terminalCode", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String terminalCode,
            @WebParam(name = "hospitalId", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String hospitalId,
            @WebParam(name = "mobileNo", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String mobileNo,
            @WebParam(name = "password", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String password,
            @WebParam(name = "socialsecurityNO", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String socialsecurityNO);

    /**
     * @param synUserName         用户名
     * @param synKey              效验码
     * @param terminalCode        终端编号
     * @param hospitalId          医院ID
     * @param mobileNo            手机号码
     * @param password            密码
     * @param socialsecurityNO    医保号
     * @Description 1.2.3    未注册判断手机号码和社保卡是否绑定
     * @return returns cn.bxd.sip.bxd.webservice.invoke.hisUser.TRegisterConfirmsExistRespond
     */
    @WebMethod(action = "http://webservice.bxd.sip.bxd.cn/registerConfirmsExist")
    @WebResult(name = "registerConfirmsExistResult", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
    @RequestWrapper(localName = "registerConfirmsExist", targetNamespace = "http://webservice.bxd.sip.bxd.cn/", className = "cn.bxd.sip.bxd.webservice.invoke.hisUser.TRegisterConfirmsExist")
    @ResponseWrapper(localName = "registerConfirmsExistResponse", targetNamespace = "http://webservice.bxd.sip.bxd.cn/", className = "cn.bxd.sip.bxd.webservice.invoke.hisUser.TRegisterConfirmsExistResponse")
    public TRegisterConfirmsExistRespond registerConfirmsExist(
            @WebParam(name = "synUserName", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String synKey,
            @WebParam(name = "terminalCode", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String terminalCode,
            @WebParam(name = "hospitalId", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String hospitalId,
            @WebParam(name = "mobileNo", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String mobileNo,
            @WebParam(name = "password", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String password,
            @WebParam(name = "socialsecurityNO", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String socialsecurityNO);

    /**
     * @param synUserName       用户名
     * @param synKey            效验码
     * @param terminalCode      终端编号
     * @param hospitalId        医院ID
     * @param mobileNo          手机号码
     * @param password          密码
     * @param socialsecurityNO  医保号
     * @param patientName       患者姓名
     * @param cardId            身份证
     * @param userNo            人员编号
     * @param medicareType      0，非医保；1,市医保；
     * @param cardinfo          卡信息（如读卡交易入参）  例如：V00113641|2000062142|0.0
     * @param overallArea       统筹区号
     * @param bankCardInfo      银行卡信息
     * @Description 1.2.4    已注册用户认证
     * @return returns cn.bxd.sip.bxd.webservice.invoke.hisUser.TCertificationUserRespond
     */
    @WebMethod(action = "http://webservice.bxd.sip.bxd.cn/certificationUser")
    @WebResult(name = "certificationUserResult", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
    @RequestWrapper(localName = "certificationUser", targetNamespace = "http://webservice.bxd.sip.bxd.cn/", className = "cn.bxd.sip.bxd.webservice.invoke.hisUser.TCertificationUser")
    @ResponseWrapper(localName = "certificationUserResponse", targetNamespace = "http://webservice.bxd.sip.bxd.cn/", className = "cn.bxd.sip.bxd.webservice.invoke.hisUser.TCertificationUserResponse")
    public TCertificationUserRespond certificationUser(
            @WebParam(name = "synUserName", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String synKey,
            @WebParam(name = "terminalCode", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String terminalCode,
            @WebParam(name = "hospitalId", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String hospitalId,
            @WebParam(name = "mobileNo", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String mobileNo,
            @WebParam(name = "password", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String password,
            @WebParam(name = "socialsecurityNO", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String socialsecurityNO,
            @WebParam(name = "patientName", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String patientName,
            @WebParam(name = "cardId", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String cardId,
            @WebParam(name = "userNo", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String userNo,
            @WebParam(name = "medicareType", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String medicareType,
            @WebParam(name = "cardinfo", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String cardinfo,
            @WebParam(name = "overallArea", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String overallArea,
            @WebParam(name = "bankCardInfo", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String bankCardInfo);

    /**
     * @param synUserName         用户名
     * @param synKey              效验码
     * @param terminalCode        终端编号
     * @param hospitalId          医院ID
     * @param socialsecurityNO    医保号
     * @param hospitalNO          医院编号
     * @param operatorNo          操作人员编号
     * @param cycleNo             周期编号
     * @param dynamic             动态库参数（签到交易为：客户端MAC地址|用户数目|）
     * @param medicareType        0，非医保；1,市医保；
     * @param cardinfo            卡信息（如读卡交易入参）
     * @Description 1.2.5    获取医保个人编号
     * @return returns cn.bxd.sip.bxd.webservice.invoke.hisUser.TGetUserNoRespond
     */
    @WebMethod(action = "http://webservice.bxd.sip.bxd.cn/getUserNo")
    @WebResult(name = "getUserNoResult", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
    @RequestWrapper(localName = "getUserNo", targetNamespace = "http://webservice.bxd.sip.bxd.cn/", className = "cn.bxd.sip.bxd.webservice.invoke.hisUser.TGetUserNo")
    @ResponseWrapper(localName = "getUserNoResponse", targetNamespace = "http://webservice.bxd.sip.bxd.cn/", className = "cn.bxd.sip.bxd.webservice.invoke.hisUser.TGetUserNoResponse")
    public TGetUserNoRespond getUserNo(
            @WebParam(name = "synUserName", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String synKey,
            @WebParam(name = "terminalCode", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String terminalCode,
            @WebParam(name = "hospitalId", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String hospitalId,
            @WebParam(name = "socialsecurityNO", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String socialsecurityNO,
            @WebParam(name = "hospitalNO", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String hospitalNO,
            @WebParam(name = "operatorNo", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String operatorNo,
            @WebParam(name = "cycleNo", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String cycleNo,
            @WebParam(name = "dynamic", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String dynamic,
            @WebParam(name = "medicareType", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String medicareType,
            @WebParam(name = "cardinfo", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String cardinfo);

    /**
     * @param synUserName          用户名
     * @param synKey               效验码
     * @param terminalCode         终端编号
     * @param hospitalId           医院ID
     * @param socialsecurityNO     医保号
     * @param hospitalNO           医院编号
     * @param operatorNo           操作人员编号
     * @param cycleNo              周期编号
     * @param dynamic              动态库参数（签到交易为：客户端MAC地址|用户数目|）
     * @param medicareType         0，非医保；1,市医保；
     * @param cardinfo             卡信息（如读卡交易入参）
     * @Description 1.2.6    获取医保卡信息
     * @return returns cn.bxd.sip.bxd.webservice.invoke.hisUser.TGetCardInfoRespond
     */
    @WebMethod(action = "http://webservice.bxd.sip.bxd.cn/getCardInfo")
    @WebResult(name = "getCardInfoResult", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
    @RequestWrapper(localName = "getCardInfo", targetNamespace = "http://webservice.bxd.sip.bxd.cn/", className = "cn.bxd.sip.bxd.webservice.invoke.hisUser.TGetCardInfo")
    @ResponseWrapper(localName = "getCardInfoResponse", targetNamespace = "http://webservice.bxd.sip.bxd.cn/", className = "cn.bxd.sip.bxd.webservice.invoke.hisUser.TGetCardInfoResponse")
    public TGetCardInfoRespond getCardInfo(
            @WebParam(name = "synUserName", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String synKey,
            @WebParam(name = "terminalCode", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String terminalCode,
            @WebParam(name = "hospitalId", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String hospitalId,
            @WebParam(name = "socialsecurityNO", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String socialsecurityNO,
            @WebParam(name = "hospitalNO", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String hospitalNO,
            @WebParam(name = "operatorNo", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String operatorNo,
            @WebParam(name = "cycleNo", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String cycleNo,
            @WebParam(name = "dynamic", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String dynamic,
            @WebParam(name = "medicareType", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String medicareType,
            @WebParam(name = "cardinfo", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String cardinfo);

    /**
     * @param synUserName             用户名
     * @param synKey                  效验码
     * @param terminalCode            终端编号
     * @param hospitalId              医院ID
     * @param mobileNo                手机号码
     * @param password                密码
     * @param THiUser                  hiUser实体对象
     * @param userNo                  人员编号
     * @param medicareType            0，非医保；1,市医保；
     * @param cardinfo                卡信息（如读卡交易入参）例如：V00113641|2000062142|0.0
     * @param overallArea             统筹区号
     * @param bankCardInfo            银行卡信息
     * @Description 1.2.7    未注册用户认证
     * @return returns cn.bxd.sip.bxd.webservice.invoke.hisUser.TRegisterUserRespond
     */
    @WebMethod(action = "http://webservice.bxd.sip.bxd.cn/registterUser")
    @WebResult(name = "registerUserResult", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
    @RequestWrapper(localName = "registerUser", targetNamespace = "http://webservice.bxd.sip.bxd.cn/", className = "cn.bxd.sip.bxd.webservice.invoke.hisUser.TRegisterUser")
    @ResponseWrapper(localName = "registerUserResponse", targetNamespace = "http://webservice.bxd.sip.bxd.cn/", className = "cn.bxd.sip.bxd.webservice.invoke.hisUser.TRegisterUserResponse")
    public TRegisterUserRespond registerUser(
            @WebParam(name = "synUserName", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String synKey,
            @WebParam(name = "terminalCode", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String terminalCode,
            @WebParam(name = "hospitalId", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String hospitalId,
            @WebParam(name = "mobileNo", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String mobileNo,
            @WebParam(name = "password", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String password,
            @WebParam(name = "THiUser", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    THiUser THiUser,
            @WebParam(name = "userNo", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String userNo,
            @WebParam(name = "medicareType", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String medicareType,
            @WebParam(name = "cardinfo", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String cardinfo,
            @WebParam(name = "overallArea", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String overallArea,
            @WebParam(name = "bankCardInfo", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String bankCardInfo);

    /**
     * @param synUserName          用户名
     * @param synKey               效验码
     * @param terminalCode         终端编号
     * @param hospitalId           医院ID
     * @param hospitalNO           医院编号
     * @param operatorNo           操作人员编号
     * @param cycleNo              周期编号
     * @param dynamic              动态库参数（签到交易为：客户端MAC地址|用户数目|）
     * @param cardinfo             卡信息（如读卡交易入参）
     * @param medicareType         0，非医保；1,市医保；
     * @Description 1.2.8    获取社保统筹区号
     * @return returns cn.bxd.sip.bxd.webservice.invoke.hisUser.TGetOverallAreaRespond
     */
    @WebMethod(action = "http://webservice.bxd.sip.bxd.cn/getOverallArea")
    @WebResult(name = "getOverallAreaResult", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
    @RequestWrapper(localName = "getOverallArea", targetNamespace = "http://webservice.bxd.sip.bxd.cn/", className = "cn.bxd.sip.bxd.webservice.invoke.hisUser.TGetOverallArea")
    @ResponseWrapper(localName = "getOverallAreaResponse", targetNamespace = "http://webservice.bxd.sip.bxd.cn/", className = "cn.bxd.sip.bxd.webservice.invoke.hisUser.TGetOverallAreaResponse")
    public TGetOverallAreaRespond getOverallArea(
            @WebParam(name = "synUserName", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String synKey,
            @WebParam(name = "terminalCode", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String terminalCode,
            @WebParam(name = "hospitalId", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String hospitalId,
            @WebParam(name = "hospitalNO", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String hospitalNO,
            @WebParam(name = "cycleNo", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String cycleNo,
            @WebParam(name = "dynamic", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    THiUser dynamic,
            @WebParam(name = "cardinfo", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String cardinfo,
            @WebParam(name = "medicareType", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String medicareType);


    /**
     * @param synUserName           用户名
     * @param synKey                效验码
     * @param terminalCode          终端编号
     * @param hospitalId            医院ID
     * @param socialsecurityNO      医保卡号
     * @param password              密码
     * @Description 1.2.9	检验医保老卡密码
     * @return returns cn.bxd.sip.bxd.webservice.invoke.hisUser.TSiCheckPassWordRespond
     */
    @WebMethod(action = "http://webservice.bxd.sip.bxd.cn/siCheckPassWord")
    @WebResult(name = "siCheckPassWordResult", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
    @RequestWrapper(localName = "siCheckPassWord", targetNamespace = "http://webservice.bxd.sip.bxd.cn/", className = "cn.bxd.sip.bxd.webservice.invoke.hisUser.TSiCheckPassWord")
    @ResponseWrapper(localName = "siCheckPassWordResponse", targetNamespace = "http://webservice.bxd.sip.bxd.cn/", className = "cn.bxd.sip.bxd.webservice.invoke.hisUser.TSiCheckPassWordResponse")
    public TSiCheckPassWordRespond siCheckPassWord(
            @WebParam(name = "synUserName", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String synUserName,
            @WebParam(name = "synKey", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String synKey,
            @WebParam(name = "terminalCode", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String terminalCode,
            @WebParam(name = "hospitalId", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String hospitalId,
            @WebParam(name = "socialsecurityNO", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String socialsecurityNO,
            @WebParam(name = "password", targetNamespace = "http://webservice.bxd.sip.bxd.cn/")
                    String password);

}
