
package cn.bxd.sip.his.webservice.hisws.invoke3.pay;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Pay", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/E:/project/sip/src/main/resources/schema/1238_Pay.wsdl")
public class Pay
    extends Service
{

    private final static URL PAY_WSDL_LOCATION;
    private final static WebServiceException PAY_EXCEPTION;
    private final static QName PAY_QNAME = new QName("http://tempuri.org/", "Pay");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/E:/project/sip/src/main/resources/schema/1238_Pay.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAY_WSDL_LOCATION = url;
        PAY_EXCEPTION = e;
    }

    public Pay() {
        super(__getWsdlLocation(), PAY_QNAME);
    }

    public Pay(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAY_QNAME, features);
    }

    public Pay(URL wsdlLocation) {
        super(wsdlLocation, PAY_QNAME);
    }

    public Pay(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAY_QNAME, features);
    }

    public Pay(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Pay(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaySoap
     */
    @WebEndpoint(name = "PaySoap")
    public PaySoap getPaySoap() {
        return super.getPort(new QName("http://tempuri.org/", "PaySoap"), PaySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaySoap
     */
    @WebEndpoint(name = "PaySoap")
    public PaySoap getPaySoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "PaySoap"), PaySoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAY_EXCEPTION!= null) {
            throw PAY_EXCEPTION;
        }
        return PAY_WSDL_LOCATION;
    }

}
