
package cn.bxd.sip.his.webservice.hisws.invoke3.pay;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PaySoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PaySoap {


    /**
     * 待交费列表
     * 
     * @param medicareMess
     * @param synKey
     * @param synUserName
     * @param patientNo
     * @param medicareType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryToPayRecipeInfoList")
    @WebResult(name = "queryToPayRecipeInfoListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryToPayRecipeInfoList", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.pay.TQueryToPayRecipeInfoList")
    @ResponseWrapper(localName = "queryToPayRecipeInfoListResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.pay.TQueryToPayRecipeInfoListResponse")
    public String queryToPayRecipeInfoList(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
        String patientNo,
        @WebParam(name = "medicareType", targetNamespace = "http://tempuri.org/")
        String medicareType,
        @WebParam(name = "medicareMess", targetNamespace = "http://tempuri.org/")
        String medicareMess);

    /**
     * 已交费列表
     * 
     * @param startDate
     * @param synKey
     * @param synUserName
     * @param endDate
     * @param patientNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryPaymentRecordList")
    @WebResult(name = "queryPaymentRecordListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryPaymentRecordList", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.pay.TQueryPaymentRecordList")
    @ResponseWrapper(localName = "queryPaymentRecordListResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.pay.TQueryPaymentRecordListResponse")
    public String queryPaymentRecordList(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
        String patientNo,
        @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 更新打票状态
     * 
     * @param synKey
     * @param synUserName
     * @param hiFeeNos
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/updateRecipeStatusStatus")
    @WebResult(name = "updateRecipeStatusStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "updateRecipeStatusStatus", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.pay.TUpdateRecipeStatusStatus")
    @ResponseWrapper(localName = "updateRecipeStatusStatusResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.pay.TUpdateRecipeStatusStatusResponse")
    public String updateRecipeStatusStatus(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "hiFeeNos", targetNamespace = "http://tempuri.org/")
        String hiFeeNos);

    /**
     * 支付
     * 
     * @param socialsecurityNO
     * @param synUserName
     * @param bankReturn
     * @param payMoney
     * @param overRecord
     * @param terminalCode
     * @param synKey
     * @param userNo
     * @param payRecord
     * @param medicareReturn
     * @param overMoney
     * @param payType
     * @param medicareType
     * @param hiFeeNos
     * @param medicareMoney
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/doPay")
    @WebResult(name = "doPayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "doPay", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.pay.DoPay")
    @ResponseWrapper(localName = "doPayResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.pay.DoPayResponse")
    public String doPay(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "hiFeeNos", targetNamespace = "http://tempuri.org/")
        String hiFeeNos,
        @WebParam(name = "payType", targetNamespace = "http://tempuri.org/")
        String payType,
        @WebParam(name = "payRecord", targetNamespace = "http://tempuri.org/")
        String payRecord,
        @WebParam(name = "payMoney", targetNamespace = "http://tempuri.org/")
        String payMoney,
        @WebParam(name = "medicareMoney", targetNamespace = "http://tempuri.org/")
        String medicareMoney,
        @WebParam(name = "socialsecurityNO", targetNamespace = "http://tempuri.org/")
        String socialsecurityNO,
        @WebParam(name = "overRecord", targetNamespace = "http://tempuri.org/")
        String overRecord,
        @WebParam(name = "overMoney", targetNamespace = "http://tempuri.org/")
        String overMoney,
        @WebParam(name = "medicareReturn", targetNamespace = "http://tempuri.org/")
        String medicareReturn,
        @WebParam(name = "bankReturn", targetNamespace = "http://tempuri.org/")
        String bankReturn,
        @WebParam(name = "terminalCode", targetNamespace = "http://tempuri.org/")
        String terminalCode,
        @WebParam(name = "userNo", targetNamespace = "http://tempuri.org/")
        String userNo,
        @WebParam(name = "medicareType", targetNamespace = "http://tempuri.org/")
        String medicareType);

    /**
     * 查询支付状态
     * 
     * @param payMoney
     * @param overRecord
     * @param socialsecurityNO
     * @param synKey
     * @param payRecord
     * @param overMoney
     * @param payType
     * @param synUserName
     * @param medicareMoney
     * @param hiFeeNos
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/queryPayStatus")
    @WebResult(name = "queryPayStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryPayStatus", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.pay.QueryPayStatus")
    @ResponseWrapper(localName = "queryPayStatusResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.pay.QueryPayStatusResponse")
    public String queryPayStatus(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "hiFeeNos", targetNamespace = "http://tempuri.org/")
        String hiFeeNos,
        @WebParam(name = "payType", targetNamespace = "http://tempuri.org/")
        String payType,
        @WebParam(name = "payRecord", targetNamespace = "http://tempuri.org/")
        String payRecord,
        @WebParam(name = "payMoney", targetNamespace = "http://tempuri.org/")
        String payMoney,
        @WebParam(name = "medicareMoney", targetNamespace = "http://tempuri.org/")
        String medicareMoney,
        @WebParam(name = "socialsecurityNO", targetNamespace = "http://tempuri.org/")
        String socialsecurityNO,
        @WebParam(name = "overRecord", targetNamespace = "http://tempuri.org/")
        String overRecord,
        @WebParam(name = "overMoney", targetNamespace = "http://tempuri.org/")
        String overMoney);

    /**
     * 查询患者未打印的发票列表
     * 
     * @param synKey
     * @param request
     * @param synUserName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryInvoiceReportList", action = "http://tempuri.org/QueryInvoiceReportList")
    @WebResult(name = "QueryInvoiceReportListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryInvoiceReportList", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.pay.QueryInvoiceReportList")
    @ResponseWrapper(localName = "QueryInvoiceReportListResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.pay.QueryInvoiceReportListResponse")
    public String queryInvoiceReportList(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        String request);

    /**
     * QueryInvoiceDetail
     * 
     * @param synKey
     * @param request
     * @param synUserName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryInvoiceDetail", action = "http://tempuri.org/QueryInvoiceDetail")
    @WebResult(name = "QueryInvoiceDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryInvoiceDetail", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.pay.QueryInvoiceDetail")
    @ResponseWrapper(localName = "QueryInvoiceDetailResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.pay.QueryInvoiceDetailResponse")
    public String queryInvoiceDetail(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        String request);

    /**
     * 票据打印
     * 
     * @param synKey
     * @param request
     * @param synUserName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdateInvoiceStatus", action = "http://tempuri.org/UpdateInvoiceStatus")
    @WebResult(name = "UpdateInvoiceStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateInvoiceStatus", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.pay.UpdateInvoiceStatus")
    @ResponseWrapper(localName = "UpdateInvoiceStatusResponse", targetNamespace = "http://tempuri.org/", className = "cn.bxd.sip.his.webservice.hisws.invoke3.pay.UpdateInvoiceStatusResponse")
    public String updateInvoiceStatus(
        @WebParam(name = "synUserName", targetNamespace = "http://tempuri.org/")
        String synUserName,
        @WebParam(name = "synKey", targetNamespace = "http://tempuri.org/")
        String synKey,
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        String request);

}
