
package cn.bxd.sip.bxd.webservice.invoke.pay;

import cn.bxd.sip.bxd.config.YmlTerminalConfig;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TPayService", targetNamespace = "http://webservice.bxd.sip.bxd.cn/", wsdlLocation = "http://172.16.100.53:7777/sip/services/Pay?wsdl")
public class TPayService
    extends Service
{

    private final static URL PAYSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAYSERVICE_EXCEPTION;
    private final static QName PAYSERVICE_QNAME = new QName("http://webservice.bxd.sip.bxd.cn/", "PayService");
    private static TPayService tPayService = null;

    static {
        YmlTerminalConfig ymlTerminalConfig = new YmlTerminalConfig();
        String payUrl = ymlTerminalConfig.getPayUrl();
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(payUrl);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYSERVICE_WSDL_LOCATION = url;
        PAYSERVICE_EXCEPTION = e;
    }

    /**
     * 单例
     * @Author  Lisheng
     * @Time 2018/10/15
     */
    public static TPayService getInstance() {
        if (tPayService == null) {
            tPayService = new TPayService();
        }
        return tPayService;
    }

    public TPayService() {
        super(__getWsdlLocation(), PAYSERVICE_QNAME);
    }

    public TPayService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYSERVICE_QNAME, features);
    }

    public TPayService(URL wsdlLocation) {
        super(wsdlLocation, PAYSERVICE_QNAME);
    }

    public TPayService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYSERVICE_QNAME, features);
    }

    public TPayService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TPayService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TIPay
     */
    @WebEndpoint(name = "PayPort")
    public TIPay getPayPort() {
        return super.getPort(new QName("http://webservice.bxd.sip.bxd.cn/", "PayPort"), TIPay.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TIPay
     */
    @WebEndpoint(name = "PayPort")
    public TIPay getPayPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.bxd.sip.bxd.cn/", "PayPort"), TIPay.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYSERVICE_EXCEPTION!= null) {
            throw PAYSERVICE_EXCEPTION;
        }
        return PAYSERVICE_WSDL_LOCATION;
    }

}
